<?php
    $title = "Your note's title here ...";
    $body = "Your note's body here ...";
    if($this->edit)
    {
        $title = $this->values['note_title'];
        $body = $this->values['note_body'];
    }
?>
<style type="text/css" media="screen">
    #editor-container {top:0; left:0; width: 100%;}
    #editor-parent {width: 100%; margin-top: 10px; }
    #editor { margin-top: 10px;}
</style>
<script>
        $(document).ready(function() {
            window.editor = ace.edit("editor");
            window.editor.setTheme("ace/theme/twilight");
            window.editor.getSession().setMode("ace/mode/markdown");
            window.editor.getSession().setTabSize(4);
            window.editor.commands.addCommand({
                name: 'save',
                bindKey: {win: 'Ctrl-S',  mac: 'Command-S'},
                exec: save
            });
            window.editor.navigateFileEnd();
            window.editor.getSession().setUseWrapMode(true);
            $(window).resize(function() {
                $("div#editor").css("height", ($(window).height() - 160) + "px").show();
                window.editor.resize();
            });
            $(window).resize();
            $(window).bind("beforeunload",function() {
                if(anything_changed())
                    return "Changes are not saved!";
            });
            $("a#switch-editor").click(function(e) {
                e.preventDefault();
                var href = String($(this).attr('href')).substr(1); // remove first `#` char.
                $("form[name='note']")
                        .append('<input type="hidden" name="submit-type" value="change-editor" />')
                        .append('<input type="hidden" name="pid" value="<?php echo $this->pid ?>" />')
                        .attr('action', href);
                save(window.editor);
            });
            $("a.note-discard").click(function(e) {
                e.preventDefault();
                var href = $(this).attr('href');
                var yes_func =function() {
                    $(window).unbind("beforeunload");
                    window.location = "/" + href;
                };
                if(!anything_changed()) {
                    yes_func();
                    return;
                }
                window.open_yesnoModal("Are you sure to <b>discard</b>?", yes_func, undefined, false);
            });
            window.ajax_start = function(){ window.open_waitModal();};
            window.ajax_stop = function() { window.open_waitModal(true);};
            window.ajax_error = function (event, jqXHR, settings, exception) { 
                var error = jqXHR
                        .responseText
                            .replace(/^[\S\s]*<body[^>]*?>/i, "")
                            .replace(/<\/body[\S\s]*$/i, "");
                window.open_errorModal(error);
            };
            $(window).ajaxStart(window.ajax_start);
            $(window).ajaxStop(window.ajax_stop);
            $(window).ajaxError(window.ajax_error);
            openOptions();
        });
        function anything_changed() {
            if("<?php echo  str_replace('"', "&quot;", $title) ?>" !== String($("#editor-title").val()).replace(/"/ig, "&quot;")) return true;
            return window.editor.session.getUndoManager().isClean() !== true;
        };
        function save(editor) {
            $(window).unbind('beforeunload');
            $("form[name='note'] input[name='note_title']").val($("#editor-title").val());
            $("form[name='note'] textarea[name='note_body']").html(editor.getValue());
            $("form[name='note'] input[name='version']").val("ace");
            $("form[name='note']").submit();
        };
        function openOptions() {
            $.ajax({
                type: "get", url: "/editor/options",
                success: function(data) {
                    setTimeout(function(data) {
                        window.open_savecloseModal(data, function(){
                            alert("Saved");
                        }, "Options");
                    }, 200, data);
                },
            });
        }
</script>
<!-- ace editor placeholder -->
<div id="editor-container" class="container-fluid">
    <div id="editor-parent">
        <ol class="breadcrumb">
            <?php $count = 0; foreach($this->route as $folder) : $active = count($this->route) == ++$count; ?>
                <li <?php echo $active?"class='active'":""?>><?php echo !$active?"<a href='/#!/d/{$folder->folder_id}.folders'>":"", $folder->folder_title, !$active?"</a>":""?></li>
            <?php endforeach;unset($count);?>
        </ol>
        <div class="input-group pull-left" style="margin-top: -10px;">
            <input type="text" name="title"  id="editor-title" class="block input form-control" placeholder="Your note's title" value="<?php echo str_replace('"', "&quot;", $title) ?>" autofocus="" required=""/>
            <span class="input-group-btn">
                <button onclick="save(window.editor);" class="btn btn-default" style="border-bottom-left-radius: 0;border-top-left-radius: 0;" tabindex="-1" title="Save">
                    <span class="glyphicon glyphicon-hdd"></span>
                </button>
                <a href="#!/d/<?php echo $this->pid ?>.notes" title="Discard" class="note-discard btn btn-warning" tabindex="-1" style="margin-left:10px;"><span class="glyphicon glyphicon-trash"></span></a>
            </span>
            <div class="pull-right">
                <div class="input-group inline" style="">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                          <span class="glyphicon glyphicon-cog"></span>  <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href='#' onclick="console.log('open a modal for configuring the editor\'s options(like font-size, warp-things, show-line#, etc) and AJX it to users\'s profile\'s setting and restore it on loading ace editor.');openOptions();"><span class="glyphicon glyphicon-th-list"></span> Editor's options</a></li>
                            <li class="divider"></li>
                            <li title="Change to classic editor"><a href="#/editor/change/to/classic?continue=<?php echo urlencode($this->request->getURI()); ?>" id="switch-editor"><span class="glyphicon glyphicon-credit-card"></span> Classic editor</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div id="editor" class="" style="display: none;"><?php echo htmlspecialchars($body) ?></div>
    </div>
</div>
<script src="/access/rte/ace/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<form action="<?php echo $this->request->getURI(); ?>" method="POST" name='note' style="display: none;">
    <input type="hidden" name="version" value="html" />
    <input type="text" name="note_title" maxlength="250" value="<?php echo $title ?>" required="required"/><br />
    <textarea rows="10" cols="80" name="note_body" ><?php echo $body ?></textarea>
    <input type="submit" value="Create" />
</form>
<?php new \core\ui\html\dialogs() ?>