<script src="/access/rte/ckeditor/ckeditor.js"></script>
<script src="/access/rte/ckeditor/adapters/jquery.js"></script>
<script>
        $( document ).ready( function() {
            $editor = $( 'textarea#editor-platform' ).ckeditor();
        } );
</script>
<div id="editor" style="margin:0">
<form action="<?php echo $this->request->getURI(); ?>" method="POST" name='note'>
    <input type="hidden" name="version" value="html" />
    <input type="text" name="note_title" maxlength="250" class="form-control" value="<?php echo isset($this->values['note_title'])?$this->values['note_title']:"" ?>" required="required"/><br />
    <textarea class="ckeditor form-control" id="editor-platform" rows="10" tabindex="1" name="note_body" style="width: 100%">
        <?php echo Michelf\MarkdownExtra::defaultTransform(isset($this->values['note_body'])?$this->values['note_body']:""); ?></textarea>
    <input type="submit" value="Create" class="form-control btn btn-primary btn-sm"/>
</form>
</div>
<!-- Sidebar placeholder -->
<div style="height: 100%;width: 30%;top:0;right: 0;position: fixed;padding: 1%;overflow: auto;">
    <legend>Settings</legend>
    <ul class="nav nav-pills" >
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="width: 100%; overflow: hidden">
                <span class="glyphicon glyphicon-list-alt"></span>
                <span class="badge"> 2 
                </span> Text Editor [<span id="rte-type">Classic</span>] <b class="caret"></b></a>
                <ul class="dropdown-menu pull-left">
                    <li><a href="<?php echo $this->request->getURI(); ?>&ui=ace">Ace</a></li>
                    <li class='active'><a href="#">Classic</a></li>
                </ul>
        </li>
    </ul>
    <legend>Tips</legend>
</div>
