<?php
    $title = "Your note's title here ...";
    $body = "Your note's body here ...";
    if($this->edit)
    {
        $title = $this->values['note_title'];
        $body = $this->values['note_body'];
    }
?>
<script src="/access/rte/ckeditor/ckeditor.js"></script>
<script src="/access/rte/ckeditor/adapters/jquery.js"></script>
<script>
        $( document ).ready( function() {
            window.editor = window.CKEDITOR.replace('note_body');
            window.editor.config.height = $(window).height() - 300;
            jQuery.fn.cke_resize = function() {
                return this.each(function() {
                    var threshold = 200;
                    var height = $(window).height() - 300;
                    if(height < threshold)
                        height = threshold;
                    $(this).next("div.cke").find(".cke_contents").css("height", height);
               });
            };
            window.CKEDITOR.on('instanceReady', function(){$("textarea.ckeditor").cke_resize();});
            $(window).resize(function() {$("textarea.ckeditor").cke_resize();});
            $(window).resize();
            $(window).bind('beforeunload', function(e){
                if(anything_changed())
                    return "Changes are not saved!";
            });
            $("a#switch-editor").click(function(e) {
                e.preventDefault();
                var href = String($(this).attr('href')).substr(1); // remove first `#` char. 
                if(false && !anything_changed()) { window.location = href; return;}
                $("form[name='note']")
                        .append('<input type="hidden" name="submit-type" value="change-editor" />')
                        .append('<input type="hidden" name="pid" value="<?php echo $this->pid ?>" />')
                        .attr('action', href);
                save();
            });
            $("a.note-discard").click(function(e) {
                e.preventDefault();
                var href = $(this).attr('href');
                var yes_func =function() {
                    $(window).unbind("beforeunload");
                    window.location = "/" + href;
                };
                if(!anything_changed()) {
                    yes_func();
                    return;
                }
                window.open_yesnoModal("Changes <b>are not</b> saved, are you sure to <b>discard</b>?", yes_func, undefined, false);
            });
        } );
        function anything_changed() {
            if("<?php echo  str_replace('"', "&quot;", $title) ?>" !== String($("#editor-title").val()).replace(/"/ig, "&quot;")) return true;
            return window.editor.checkDirty();
        }
        function save() {
            $(window).unbind('beforeunload');
            $("form[name='note']").submit();
        }
</script>
<style type="text/css">
    #editor-container {margin-top: 10px;margin-bottom: 10px;}
</style>
<!-- ckeditor placeholder -->
<div id="editor-container" class="container-fluid">
    <form action="<?php echo $this->request->getURI(); ?>" method="POST" name='note'>
        <input type="hidden" name="version" value="html" />
        <div id="editor-parent">
            <ol class="breadcrumb">
                <?php $count = 0; foreach($this->route as $folder) : $active = count($this->route) == ++$count; ?>
                    <li <?php echo $active?"class='active'":""?>><?php echo !$active?"<a href='/#!/d/{$folder->folder_id}.folders'>":"", $folder->folder_title, !$active?"</a>":""?></li>
                <?php endforeach;unset($count);?>
            </ol>
            <div class="input-group pull-left" style="margin-top: -10px;">
                <input type="text" name="note_title"  id="editor-title" class="block input form-control" placeholder="Your note's title" value="<?php echo str_replace('"', "&quot;", isset($this->values['note_title'])?$this->values['note_title']:"") ?>" autofocus="" maxlength="300"/>
                <span class="input-group-btn">
                    <button onclick="save();" class="btn btn-default" style="border-bottom-left-radius: 0;border-top-left-radius: 0;" tabindex="-1" title="Save">
                        <span class="glyphicon glyphicon-hdd"></span>
                    </button>
                    <a href="#!/d/<?php echo $this->pid ?>.notes" title="Discard" class="note-discard btn btn-warning" tabindex="-1" style="margin-left:10px;"><span class="glyphicon glyphicon-trash"></span></a>
                </span>
                <div class="pull-right">
                    <div class="input-group inline" style="">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                              <span class="glyphicon glyphicon-cog"></span>  <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li><a href='#' onclick="alert('open a modal for configuring the editor\'s options(like font-size, warp-things, show-line#, etc) and AJX it to users\'s profile\'s setting and restore it on loading ace editor.');"><span class="glyphicon glyphicon-th-list"></span> Editor's options</a></li>
                                <li class="divider"></li>
                                <li title="Change to Ace editor"><a href="#/change/editor/to/ace?continue=<?php echo urlencode($this->request->getURI()); ?>" id="switch-editor"><span class="glyphicon glyphicon-credit-card"></span> Ace editor</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix" style="margin: 10px;"></div>
            <textarea class="ckeditor form-control hidden" id="editor-platform" tabindex="1" name="note_body" style="width: 100%;"><?php
                # invoke the markdown initiliazer
                $mdi = new \core\ui\markdown\markdownInitiliazer;
                # execute the initliazer
                $mdi->Execute();
                # markdown the context
                echo \Markdown($body);
            ?></textarea>
        </div>
    </form>
</div>
<?php new \core\ui\html\dialogs() ?>