<?php if(!\core\db\models\user::IsSignedin()) return; ?>
<ol class="breadcrumb">
<?php
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route));?>
        <li <?php echo $is_active?" class='active'":""?>><?php echo !$is_active?"<a href='/directory/{$folder->folder_id}.{$this->request->type}'>":"";echo $folder->folder_title;echo !$is_active?"</a>":""?></li>
<?php endforeach; ?>
</ol>
<ul class="nav nav-pills pull-right">
    <li class="dropdown pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Create <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
                <span class="glyphicon glyphicon-folder-close"></span>
                <a href="/ops/new/folder/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("folder", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"> Folder</a>
            </li>
            <li>
                <a href="/ops/new/note/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("note", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"> Note</a>
            </li>
            <li>
                <a href="/ops/new/link/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("link", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"> Link</a>
            </li>
        </ul>
    </li>
</ul>
<div style="float: left">
        <a href="/ops/new/folder/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("folder", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>">
            Create new folder
        </a>| 
        <a href="/ops/new/link/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("link", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>">
            Create new link
        </a>| 
        <a href="/ops/new/note/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("note", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>">
            Create new note
        </a>
</div>
<div style="float: left">
    <a href="/trashes">Trashes</a> | 
    <a href="/archives">Archives</a> |
    <a href="/shared">Shared</a>
</div>
<?php
    $this->RenderPartial("item_table", array("folders" => $this->folders, "links"=> $this->links, "notes" => $this->notes));