<div id="move-global-container">
<?php
$this->folders_list = isset($this->folders_list) ? $this->folders_list : array();
foreach(array("items_string", "origin_pid", "current_pid", "folders_list", "route_path", "items_id", "sort", "order") as $attr) {
    if(!isset($this->$attr))
        throw new zinux\kernel\exceptions\notImplementedException("The argument `$attr` has not supplied");
}
$get_folder_title = function(\core\db\models\folder $folder, $title_max_len = 60){
    $title = $folder->getItemTitle();
    if(strlen($title) > $title_max_len)
        $title =substr($title, 0, $title_max_len - 5)."[...]";
    return $title;
};
$address = array();
echo "<div id='move-container'>";
echo "<ol class='breadcrumb'>";
foreach($this->route_path as $index => $path) {
    $is_active = ($index === count($this->route_path) - 1);
    $r = new stdClass;
    $r->is_active = $is_active;
    $r->data_id = $path->getItemID();
    $r->title = $get_folder_title($path, 30);
    $address[] = $r;
    echo "<li class='".($r->is_active ? "active" : "")."'>";
    if(!$is_active) echo "<a href='#' data-id='$r->data_id'>";
    echo $r->title;
    if(!$is_active)  echo "</a>";
    echo "</li>";
}
echo "</ol>";
$current_folder = end($this->route_path);
$self_move = ($this->origin_pid == $current_folder->folder_id);
echo "<dl class='move-list'>";
    echo "<dt ".($this->current_pid != "0" ? "data-id='{$current_folder->parent_id}'" : "" )."><span class='glyphicon glyphicon-folder-open'></span>&nbsp;&nbsp;{$get_folder_title($current_folder)}</dt>";
foreach($this->folders_list as $folder) {
    $in_valid_push = in_array($folder->getItemID(), $this->items_id);
    echo "<dd ".(!$in_valid_push ? "data-id='{$folder->folder_id}'" : "class='invalid-push' data-toggle='tooltip' data-placement='top'  title='Cannot move into itself!'")."><span class='glyphicon glyphicon-folder-close'></span>&nbsp;&nbsp;{$get_folder_title($folder)}</dd>";
}
echo "</dl>";
if(!count($this->folders_list)) {
?>
<div style="border: 1px solid #DDD; width: 100%; height: 40px;padding: 10px;margin-top: -20px;font-weight: bold" class="text-center">
    Empty Folder
</div>
<?php
}
?>
<script type="text/javascript">
    document.self_move = <?php echo $self_move ? "true" :  "false" ?>;
    $(document).ready(function(){
        $("button[name='move-here-action']:not(.disabled)").unbind('click').click(function(){
            <?php if(!isset($this->request->params["get_address_only"])) : ?>
            var submit_data = $.extend({}, window.movement_ajax_default_data, {cpid: <?php echo $this->current_pid ?>, submit: 1});
            window.top.open_waitModal();
            $.ajax({
                global: false,
                type: "POST",
                url: "/ops/move?<?php echo zinux\kernel\security\security::__get_uri_hash_string(array($this->type, $this->origin_pid))?>",
                data: submit_data,
                success: function(data){
            <?php endif; ?>
                    if(typeof(window.movement_callback) === "function")
                        window.movement_callback(<?php echo json_encode($address) ?>);
            <?php if(!isset($this->request->params["get_address_only"])) : ?>
                    else
                        window.location.reload();
                }
            }).fail(function(xhr){
                window.top.close_modal();
                setTimeout(function() { window.top.open_errorModal(xhr.responseText, -1, true); setTimeout(function(){ window.location.reload(); }, 2500);}, 500);
            }).always(function(){
                window.top.open_waitModal(true);
            });
            <?php endif; ?>
        });
        $.fn.insertAt=function(e,t){var n=this.children().size();if(e<0){e=Math.max(0,n+1+e);}this.append(t);if(e<n){this.children().eq(e).before(this.children().last());}return this;};
        var new_folder = function(){
            $(this).off();
            $(this).data("ineffect", 1).addClass('disabled');
            var $n = $("<dd><input type='textbox' class='form-control' value='Untitled Folder' name='new-folder' style='display:inline;width:90%!important'/><small style='margin-left:10px;margin-top:7px;'><a class='iclose' href='#'>close</a></small><div class='clearfix'></div></dd>").addClass("new-folder").css("padding", 0);
            $this = $(this);
            var clearout = function() { $("dl.move-list dd.new-folder").remove(); $this.on('click', new_folder).removeClass('disabled'); return false;};
            $n.find('input[name=new-folder]').keydown(function(e) {
                if (e.keyCode === 10 || e.keyCode === 13) {
                    $(this).attr("readonly", "true");
                    $.ajax({
                        global: false,
                        url: "/new/folder/?pid=<?php echo $current_folder->folder_id, \zinux\kernel\security\security::__get_uri_hash_string(array("folder", $current_folder->folder_id,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>",
                        type: "POST",
                        data: {
                            folder_title: $(this).val(),
                            ajax: 1,
                            json: 1
                        },
                        dataType: "JSON",
                        success: function(data) {
                            $("<dd data-id='"+data.id+"'><span class='glyphicon glyphicon-folder-close'></span>&nbsp;&nbsp;"+data.title+"</dd>").addClass("recently-created").insertAfter("dl.move-list dt");
                            window.init_movements();
                            clearout();
                            setTimeout(function(){$(".recently-created").removeClass("recently-created")}, 2500);
                            if(typeof(window.apply_change) === "function")
                                window.apply_change(window.APPLY_NEW, {origin: data.html, type: "folder"});
                        }
                    }).fail(function(xhr){
                        window.close_modal();
                        setTimeout(function() { window.open_errorModal(xhr.responseText, -1, true); }, 500);
                    }).always(function(){
                        $(this).removeAttr("readonly");
                    });
                }
            });
            $("dl.move-list").insertAt(1, $n);
            $('dl.move-list .new-folder .iclose').click(clearout);
            setTimeout(function(){$n.find("input").select().focus();}, 200);
        };
        $("button[name='new-folder-action']:not(.disabled)").off('click').on('click', new_folder);
    });
</script>
<hr />
<div class="action-btns">
    <button class="btn btn-default btn-sm pull-left" data-dismiss="modal" onclick="delete window.movement_ajax_default_data;setTimeout(function(){$('#move-global-container').remove();}, 1000);" name="move-here-cancel"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
    <div class="pull-right">
    <button class="btn btn-success btn-sm" type="submit" name="new-folder-action"><span class="glyphicon glyphicon-plus"></span> Folder</button>
    <button class="btn btn-primary btn-sm" type="submit" name="move-here-action"><span class="glyphicon glyphicon-save"></span> Move Here</button>
    </div>
</div>
<?php
echo "</div>";
if(isset($this->request->params["dive"])) return;
?>
<script type="text/javascript">
    (function(){
        window.movement_ajax_default_data = {
                    items:<?php echo $this->items_string ?>,
                    pid: <?php echo $this->origin_pid ?>,
                    type: <?php echo json_encode($this->type) ?>,
                    order: <?php echo json_encode($this->order) ?>,
                    sort: <?php echo json_encode($this->sort) ?>
                };
        window.init_movements = function() {
            $('[data-toggle="tooltip"]').tooltip();
            if(typeof(document.self_move) !== "undefined" && document.self_move)
                $("button[name='move-here-action']").addClass("disabled");
            else
                $("button[name='move-here-action']").removeClass("disabled");
            $("dl.move-list [data-id], .breadcrumb a[data-id]").click(function(e){
                e.preventDefault();
                window.top.open_waitModal();
                <?php $validators = array($this->type, $this->origin_pid); ?>
                <?php if(isset($this->request->params["get_address_only"])) $validators[] = 1;?>
                var data = {cpid: $(this).attr('data-id'), dive: 1<?php echo isset($this->request->params["get_address_only"]) ? ", get_address_only: 1" : "" ?>};
                $.ajax({
                    global: false,
                    url: "/ops/move?<?php echo zinux\kernel\security\security::__get_uri_hash_string($validators)?>",
                    data: $.extend({}, window.movement_ajax_default_data, data),
                    success: function(data){
                        $("#move-container").replaceWith(data);
                        init_movements();
                    }
                }).fail(function(xhr){
                    window.top.close_modal();
                    setTimeout(function() { window.top.open_errorModal(xhr.responseText, -1, true); }, 500);
                }).always(function(){
                    window.top.open_waitModal(true);
                });
            });
        };
        init_movements();
    })(jQuery);
</script>
<div class="clearfix"></div>
<style type="text/css">@media screen and (min-height:0) and (max-height:700px){dl.move-list{max-height:300px}}@media screen and (min-height:701px) and (max-height:800px){dl.move-list{max-height:450px}}@media screen and (min-height:801px){dl.move-list{max-height:500px}}.breadcrumb li.active{color:#888}dl.move-list{overflow:auto}.action-btns button{font-weight:700}dl.move-list dd,dl.move-list dt{height:40px;padding:8px;margin:1px;vertical-align:central;cursor:pointer;overflow:hidden;word-break:break-all}dl.move-list dd:hover,dl.move-list dt:hover{background-color:#e6e6e6;border:1px solid #a5a5a5}dl.move-list .invalid-push{color:#DDD;cursor:default}dl.move-list .invalid-push:hover{border:1px solid #DDD;background-color:transparent!important}dl.move-list dd{margin-left:20px}
    
dl.move-list dd.new-folder:hover {background-color:initial;border: initial}
dl.move-list dd.new-folder input{border: 1px solid #66AFE9}
dl.move-list dd.recently-created {font-weight: bold}
</style>
</div>