<?php
$this->folders_list = isset($this->folders_list) ? $this->folders_list : array();
foreach(array("items_string", "origin_pid", "current_pid", "folders_list", "route_path") as $attr) {
    if(!isset($this->$attr))
        throw new zinux\kernel\exceptions\notImplementedException("The argument `$attr` has not supplied");
}
echo "<ol class='breadcrumb'>";
foreach($this->route_path as $index => $path) {
    $is_active = ($index === count($this->route_path) - 1);
    echo "<li class='".($is_active ? "active" : "")."'>";
    if(!$is_active) echo "<a href='#'>";
    echo $path->getItemTitle();
    if(!$is_active)  echo "</a>";
    echo "</li>";
}
echo "</ol>";
$current_folder = end($this->route_path);
$get_folder_title = function(\core\db\models\folder $folder){
    $title_max_len = 80;
    $title = $folder->getItemTitle();
    if(strlen($title) > $title_max_len)
        $title =substr($title, 0, $title_max_len - 5)."[...]";
    return $title;
};
echo "<dl class='move-list'>";
if($this->current_pid != "0")
    echo "<dt><span class='glyphicon glyphicon-folder-open'></span>&nbsp;&nbsp;{$get_folder_title($current_folder)}</dt>";
//$this->folders_list =array_merge($this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list, $this->folders_list);
foreach($this->folders_list as $folder) {
    # no-recursive movement allowed
    if($current_folder->folder_id == $folder->folder_id) continue;
    echo "<dd><span class='glyphicon glyphicon-folder-close'></span>&nbsp;&nbsp;{$get_folder_title($folder)}</dd>";
}
echo "</dl>";
if(isset($this->request->params["dive"])) return;
?>
<hr />
<div class="action-btns">
    <button class="btn btn-default btn-sm pull-left" data-dismiss="modal" >Cancel</button>
    <button class="btn btn-primary btn-sm pull-right">Move Here</button>
</div>
<script type="text/javascript">
    (function(){
        $.ajax({
            global: false,
            data: {dive: 1, items:<?php echo $this->items_string ?>}
        });
    })(jQuery);
</script>
<div class="clearfix"></div>
<style type="text/css">
    @media screen and (min-height: 0px) and (max-height: 700px) {
        dl.move-list { max-height: 300px;}
    }
    @media screen and (min-height: 701px) and (max-height: 800px) {
        dl.move-list { max-height: 450px;}
    }
    @media screen and (min-height: 801px) {
        dl.move-list { max-height: 500px;}
    }
    .breadcrumb li.active { color: #888; }
    dl.move-list {
        overflow: auto;
    }
    dl.move-list dt,
    dl.move-list dd {
        height: 40px;
        padding: 8px;
        margin: 1px;
        vertical-align: central;
        cursor: pointer;
        overflow: hidden;
        word-break: break-all;
    }
    dl.move-list dt:hover,
    dl.move-list dd:hover {
        background-color: #e6e6e6;
        border: 1px solid #a5a5a5;
    }
    dl.move-list dd {
        margin-left: 20px;
    }
</style>