<div id="move-global-container">
<?php
$this->folders_list = isset($this->folders_list) ? $this->folders_list : array();
foreach(array("items_string", "origin_pid", "current_pid", "folders_list", "route_path", "items_id") as $attr) {
    if(!isset($this->$attr))
        throw new zinux\kernel\exceptions\notImplementedException("The argument `$attr` has not supplied");
}
$get_folder_title = function(\core\db\models\folder $folder, $title_max_len = 60){
    $title = $folder->getItemTitle();
    if(strlen($title) > $title_max_len)
        $title =substr($title, 0, $title_max_len - 5)."[...]";
    return $title;
};
echo "<div id='move-container'>";
echo "<ol class='breadcrumb'>";
foreach($this->route_path as $index => $path) {
    $route_ids[] = $path->getItemID();
    $is_active = ($index === count($this->route_path) - 1);
    echo "<li class='".($is_active ? "active" : "")."'>";
    if(!$is_active) echo "<a href='#' data-id='$path->folder_id'>";
    echo $get_folder_title($path, 30);
    if(!$is_active)  echo "</a>";
    echo "</li>";
}
echo "</ol>";
$current_folder = end($this->route_path);
$self_move = ($this->origin_pid == $current_folder->folder_id);
echo "<dl class='move-list'>";
    echo "<dt ".($this->current_pid != "0" ? "data-id='{$current_folder->parent_id}'" : "" )."><span class='glyphicon glyphicon-folder-open'></span>&nbsp;&nbsp;{$get_folder_title($current_folder)}</dt>";
foreach($this->folders_list as $folder) {
    $in_valid_push = in_array($folder->getItemID(), $this->items_id);
    echo "<dd ".(!$in_valid_push ? "data-id='{$folder->folder_id}'" : "class='invalid-push' title='Cannot move into this!'")."><span class='glyphicon glyphicon-folder-close'></span>&nbsp;&nbsp;{$get_folder_title($folder)}</dd>";
}
echo "</dl>";
if(!count($this->folders_list)) {
?>
<div style="border: 1px solid #DDD; width: 100%; height: 40px;padding: 10px;margin-top: -20px;font-weight: bold" class="text-center">
    Empty Folder
</div>
<?php
}
?>
<script type="text/javascript">
    document.self_move = <?php echo $self_move ? "true" :  "false" ?>;
    $(document).ready(function(){
        $("button[name='move-here-action']:not(.disabled)").unbind('click').click(function(){
            var submit_data = $.extend({}, window.movement_ajax_default_data, {cpid: <?php echo $this->current_pid ?>, submit: 1});
            window.top.open_waitModal();
            $.ajax({
                global: false,
                type: "POST",
                url: "/ops/move?<?php echo zinux\kernel\security\security::__get_uri_hash_string(array($this->type, $this->origin_pid))?>",
                data: submit_data,
                success: function(data){
                    if(typeof(window.movement_callback) === "function")
                        window.movement_callback();
                    else
                        window.location.reload();
                }
            }).fail(function(xhr){
                window.top.close_modal();
                setTimeout(function() { window.top.open_errorModal(xhr.responseText, -1, true); }, 500);
            }).always(function(){
                window.top.open_waitModal(true);
            });
        });
    });
</script>
<hr />
<div class="action-btns">
    <button class="btn btn-default btn-sm pull-left" data-dismiss="modal" onclick="delete window.movement_ajax_default_data;setTimeout(function(){$('#move-global-container').remove();}, 1000);" name="move-here-cancel">Cancel</button>
    <button class="btn btn-primary btn-sm pull-right" type="submit" name="move-here-action">Move Here</button>
</div>
<?php
echo "</div>";
if(isset($this->request->params["dive"])) return;
?>
<script type="text/javascript">
    (function(){
        window.movement_ajax_default_data = {
                    items:<?php echo $this->items_string ?>,
                    pid: <?php echo $this->origin_pid ?>,
                    type: <?php echo json_encode($this->type) ?>
                };
        var init_movements = function() {
            if(typeof(document.self_move) !== "undefined" && document.self_move)
                $("button[name='move-here-action']").addClass("disabled");
            else
                $("button[name='move-here-action']").removeClass("disabled");
            $("dl.move-list [data-id], .breadcrumb a[data-id]").click(function(e){
                e.preventDefault();
                window.top.open_waitModal();
                $.ajax({
                    global: false,
                    url: "/ops/move?<?php echo zinux\kernel\security\security::__get_uri_hash_string(array($this->type, $this->origin_pid))?>",
                    data: $.extend({}, window.movement_ajax_default_data, {cpid: $(this).attr('data-id'), dive: 1}),
                    success: function(data){
                        $("#move-container").replaceWith(data);
                        init_movements();
                    }
                }).fail(function(xhr){
                    window.top.close_modal();
                    setTimeout(function() { window.top.open_errorModal(xhr.responseText, -1, true); }, 500);
                }).always(function(){
                    window.top.open_waitModal(true);
                });
            });
        };
        init_movements();
    })(jQuery);
</script>
<div class="clearfix"></div>
<style type="text/css">@media screen and (min-height:0) and (max-height:700px){dl.move-list{max-height:300px}}@media screen and (min-height:701px) and (max-height:800px){dl.move-list{max-height:450px}}@media screen and (min-height:801px){dl.move-list{max-height:500px}}.breadcrumb li.active{color:#888}dl.move-list{overflow:auto}.action-btns button{font-weight:700}dl.move-list dd,dl.move-list dt{height:40px;padding:8px;margin:1px;vertical-align:central;cursor:pointer;overflow:hidden;word-break:break-all}dl.move-list dd:hover,dl.move-list dt:hover{background-color:#e6e6e6;border:1px solid #a5a5a5}dl.move-list .invalid-push{color:#DDD;cursor:default}dl.move-list .invalid-push:hover{border:0;background-color:transparent!important}dl.move-list dd{margin-left:20px}</style>
</div>