<div id="new-folder-ui">
    <ol style="color:red;">
    <?php foreach ($this->errors as $error) : ?>
        <li><?php echo $error ?></li>
    <?php endforeach; ?>
    </ol>
    <!--div class="modal fade in" id="new-folder-modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?php echo !isset($this->values['folder_title'])?"New":"Edit" ?> Folder</h4>
          </div>
          <div class="modal-body"-->
            <form action="<?php echo $this->request->GetURI() ?>" method="POST" class="form">
            <?php if(false && isset($this->request->params["continue"])) : ?>
                <input type="hidden" name="continue" value="<?php echo $this->request->params["continue"]; ?>" />
            <?php endif; ?>
                <div class="input-group">
                  <input type="text" class="form-control" name="folder_title" maxlength="250" placeholder="Folder's title" value="<?php echo isset($this->values['folder_title'])?$this->values['folder_title']:"" ?>">
                  <span class="input-group-btn">
                  <button type="submit" class="btn btn-primary" >Create</button>
                  </span>
                </div><!-- /input-group -->
            </form>
          <!--/div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </div><!-- /.modal-content -->
      <!--/div><!-- /.modal-dialog -->
    <!--/div><!-- /.modal -->
    <script>
        $(document).ready(function(){
            $("#new-folder-ui form" ).submit(function(e) {
                e.preventDefault();
                $.ajax({
                    type: $(this).attr("method"),
                    url: $(this).attr("action"),
                    data: $(this).serialize()+"&suppress_redirection=1&"+$(this).attr("action").split("?")[1]
                });
            });
            $("input[name='folder_title']").focus();
        });
    </script>
</div>