<ol style="color:red;">
<?php foreach ($this->errors as $error) : ?>
    <li><?php echo $error ?></li>
<?php endforeach; ?>
</ol>
<form action="<?php echo $this->request->GetURI() ?>" method="POST">
    <input type="text" name="folder_title" maxlength="250" placeholder="Folder's title" value="<?php echo isset($this->values['folder_title'])?$this->values['folder_title']:"" ?>"/>
    <input type="submit" value="Create" />
</form>