<?php $this->edit = isset($this->edit)?$this->edit:0; ?>
<?php if(count($this->errors)): ?>
<ol class='text-danger' style="list-style-image: url('/access/img/bullet.png');padding:0;margin:10px 35px 0;font-weight: bold">
<?php foreach ($this->errors as $error) : ?>
    <li><?php echo $error ?></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<div class="container">
    <ul class="nav nav-tabs" id="preview-tab">
        <li class="active"><a href="#" pref="context">Context</a></li>
        <li><a href="#" pref="preview">Preview</a></li>
    </ul>
</div>
<div id="newnote-editor-container" class="container">
<?php
    $profile = \core\db\models\profile::getInstance(\core\db\models\user::getInstance()->user_id);
    if(!isset($this->request->params["ui"]))
        $this->request->params["ui"] =
            !$profile->getSetting("/rte/type")?"classic":$profile->getSetting("/rte/type");
    $profile->setSetting("/rte/type", $this->request->params["ui"]);
    $this->layout->setLayout('editor');
    $ui = $this->request->params["ui"];
    if($this->edit && isset($this->editor_type) && !isset($this->request->params["force-ui"])) {
        switch($this->editor_type) {
            case 0: $ui = "html"; break;
            case 1: $ui = "ace"; break;
            default: throw new \zinux\kernel\exceptions\invalidArgumentException("Undefined editor type `$this->editor_type`");
        }
    }
    switch($ui)
    {
        default:
        case "classic":
            $this->RenderPartial("tinyMCE");
            break;
        case "ace":
            $this->RenderPartial("ace");
            break;
    }
?>
    <div id="note-preview" style="display: none;margin: 10px;"></div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        // validate if the `window.getEditorTEXT()` is defined in rendered views??
        if( typeof(window.getNoteTitle) === "undefined" ||
            typeof(window.getNoteTitle) !== "function") { console.error("Invalid editor interface"); return; }
        if( typeof(window.getNoteContext) === "undefined" ||
            typeof(window.getNoteContext) !== "function") { console.error("Invalid editor interface"); return; }
        // bind a click handler for preview/content links
        $(".nav#preview-tab a").click(function(e){
            e.preventDefault();
            $(".nav#preview-tab li.active").removeClass("active");
            $(this).parent().addClass("active");
            switch(String($(this).attr('pref')).toLocaleString()){
                case "preview":
                    $("#editor-container").slideUp();
                    window.open_waitModal();
                    $.ajax({
                        type: "POST",
                        url: "/editor/preview",
                        data: "t=" + window.getNoteTitle() + "&b="+window.getNoteContext(),
                        global: false,
                        success: function(data) {
                            $("#newnote-editor-container #note-preview")
                                    .html(data)
                                    .show();
                        }
                    }).fail(function(xhr) {
                        window.open_errorModal(xhr.responseText, -1, true);
                    }).always(function() {
                        window.open_waitModal(true);
                    });
                    break;
                case "context":
                    $("#editor-container").slideDown();
                    $("#newnote-editor-container #note-preview")
                                .html("")
                                .hide();
                    break;
                default: console.error("Undefined preference `"+$(this).attr('pref')+"`");
            }
        });
        setTimeout(function(){$(".nav#preview-tab a[pref='preview']").click();}, 500);
    });
</script>