<?php $this->edit = isset($this->edit)?$this->edit:0; ?>
<?php if(count($this->errors)): ?>
<ol style="color:red;">
<?php foreach ($this->errors as $error) : ?>
    <li><?php echo $error ?></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<style type="text/css" media="screen">
    #editor { position: fixed; top:0; right: 0; bottom: 0; left: 0; width: 70%;}
</style>
<?php
    $profile = \core\db\models\profile::load(\core\db\models\user::getInstance()->user_id);
    if(!@$profile->settings->rte)
         $profile->settings->rte = new stdClass;
    if(!isset($this->request->params["ui"]))
        $this->request->params["ui"] = 
            !@$profile->settings->rte->type?"classic":$profile->settings->rte->type;
    $profile->settings->rte->type = $this->request->params["ui"];
    $profile->save();
    switch($this->request->params["ui"])
    {
        default:
        case "classic":
            $this->RenderPartial("ckeditor");
            break;
        case "ace":
            $this->RenderPartial("ace");
            break;
    }
?>
<script>
    $(document).ready(function(){
        $("form[name='note']").hide();
    });
</script>
<script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
<form action="<?php echo $this->request->getURI(); ?>" method="POST" name='note'>
    <input type="hidden" name="version" value="html" />
    <input type="text" name="note_title" maxlength="250" value="<?php echo isset($this->values['note_title'])?$this->values['note_title']:"" ?>" required="required"/><br />
    <textarea rows="10" cols="80" name="note_body" ><?php echo isset($this->values['note_body'])?$this->values['note_body']:"" ?></textarea>
    <input type="submit" value="Create" />
</form>
