<?php
    $title = "Your note's title here ...";
    $body = "Your note's body here ...";
    $tags = "";
    if($this->edit)
    {
        $title = $this->values['note_title'];
        $body = $this->values['note_body'];
        $note_id = $this->values['note_id'];
        $tags = "";
        foreach($this->values["tags"] as $tag) {
            $tags = "$tags, $tag->tag_value";
        }
    }
    $this->edit = $this->edit && !$this->is_using_buffer;
?>
<script src="/access/js/shortcut.min.js"></script>
<script src="/access/rte/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
        $( document ).ready( function() {
            var height = $(window).height() - 360;
            if(height < 420)
                height = 420;
            tinymce.init({
                selector: "textarea",
                height : height,
                plugins: [
                    "advlist autolink lists link image charmap print preview anchor",
                    "searchreplace visualblocks code fullscreen",
                    "insertdatetime media table contextmenu paste"
                ],
                toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
                toolbar1: "newdocument fullpage | cut copy paste | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | styleselect formatselect fontselect fontsizeselect",
                toolbar2: "searchreplace | bullist numlist | outdent indent blockquote | undo redo | link unlink anchor image media code | inserttime preview | forecolor backcolor | table | hr removeformat | subscript superscript | charmap emoticons | print fullscreen | ltr rtl | spellchecker",
                 setup: function(ed) {
                     // the editor save function
                     ed.addShortcut("ctrl+s", "Save", save);
                 }
            });
            $(window).bind('beforeunload', function(e){
                if(anything_changed())
                    return "Changes are not saved!";
            });
            $("a#switch-editor").click(function(e) {
                e.preventDefault();
                var $this = $(this);
<?php if($this->edit) : ?>
                window.open_yesnoModal(
                        "<b>Switching between editors can cause incompatibility issues, and can cause note's pure text seem agly, and might make note development harder.<br /> Are you sure do you want to change the editor?</b>", 
                        function() {
<?php endif; ?>
                            var href = String($this.attr('href')).substr(1); // remove first `#` char.
                            if(false && !anything_changed()) { window.location = href; return;}
                            $("form[name='note']")
                                    .append('<input type="hidden" name="submit-type" value="change-editor" />')
                                    .append('<input type="hidden" name="pid" value="<?php echo $this->pid ?>" />')
                                    .attr('action', href);
                            document.switch_editor = true;
                            save(true);
<?php if($this->edit) : ?>
                        }, undefined, false);
<?php endif; ?>
            });
            $("a.note-discard").click(function(e) {
                e.preventDefault();
                var href = $(this).attr('href');
                var yes_func =function() {
                    $(window).unbind("beforeunload");
                    window.location = href;
                };
                if(!anything_changed()) {
                    yes_func();
                    return;
                }
                window.open_yesnoModal("Changes <b>are not</b> saved, are you sure to <b>discard</b>?", yes_func, undefined, false);
            });
            window.getNoteContext = function() {
                return tinymce.get('editor').getContent();
            };
            window.getNoteTitle = function() {
                return $("#editor-title").val();
            };
        } );
        function anything_changed() {
            if(<?php echo json_encode($title) ?> !== String($("#editor-title").val()).replace(/"/ig, "&quot;")) return true;
            if(is_tags_changed() || $("form[name='note'] input[name='cd']").length) return true;
            return <?php echo @$this->is_using_buffer? "true || " : ""  ?>tinymce.get('editor').isDirty();
        }
        window.saveAPI = function() {
            save();
        };
        function save(force_save) {
            if(<?php echo $this->edit? "false" : "true" ?> && typeof(document.switch_editor) === "undefined" && typeof(document.tagit_callback) === "undefined") {
                document.tagit_callback = function(){
                    var o = document.tagit_callback_params;
                    if(typeof(o) === "undefined")
                        throw "undefined callback obj";
                    __save(o._force_save);
                    delete document.tagit_callback_params, document.tagit_callback;
                };
                document.tagit_callback_params = {
                    _force_save: force_save
                };
                tagit();
            } else {
                __save(force_save);
            }
        };
        function __save(force_save) {
            $(window).unbind('beforeunload');
            if(typeof(force_save) === "undefined") force_save = false;
<?php if(strtolower($this->request->action->name) != "new") : ?>
            if(!(force_save || anything_changed())) {
                $("a.note-discard").click();
                return;
            }
<?php endif; ?>
            $("form[name='note']").submit();
        };
        window.movement_callback = function(address){
            window.close_modal();
            if(address.length === 0) { setTimeout(function(){ window.open_errorModal("Couldn't fetch the proper address!"); }, 500); return; }
            var $epb = $("#editor-parent .breadcrumb").find("li:not(.cd)").remove().end();
            var active_id = -1;
            var tags = [];
            address.reverse().forEach(function(e) {
                var $e = $("<li>");
                if(!e.is_active) {
                    $e.append($("<a>"));
                    $e.find("a").attr("data-id", e.data_id).text(e.title);
                } else { active_id = e.data_id;$e.addClass("active").text(e.title); }
                $epb.prepend($e);
                if(e.data_id)
                    tags.push(e.title);
            });
            $("<input type='hidden' name='cd' value='"+active_id+"' />").appendTo("form[name='note']");
            <?php if(!$this->edit): ?>
            add_tags(tags, true);
            <?php endif; ?>
        };
        function change_path() {
            <?php $profile =\core\db\models\profile::getInstance(); ?>
            <?php $s = $profile->getSetting("/general/directory-tree-sort-type"); ?>
            <?php $is_valid_s = ($s && is_array($s) && count($s) === 2); ?>
            <?php $s = ($is_valid_s ? $s : array("defaultHeadIndex" => 2, "defaultHeadOrder" => 0)); ?>
            $.ajax({
                global: false,
                type: "GET",
                url: "/ops/move?init=1&pid=<?php echo end($this->route)->getItemID() ?>&get_address_only=1",
                data: "type=folder&items[]=-1;1;1&sort=<?php echo $s["defaultHeadIndex"] - 1?>&order=<?php echo $s["defaultHeadOrder"] ?>"+<?php echo json_encode(zinux\kernel\security\security::__get_uri_hash_string(array("folder", end($this->route)->getItemID(), 1))) ?>,
                success: function(data){
                    window.top.open_dialogModal(data);
                }
            }).fail(function(xhr){
                setTimeout(function() { window.top.open_errorModal(xhr.responseText, -1, true); }, 500);
            }).always(function(){
                window.top.open_waitModal(true);
            });
        };
</script>
<style type="text/css">
    #editor-container {margin-top: 10px;margin-bottom: 10px;}
    .mce-panel { border: 1px solid #e6e6e6!important;}
</style>
<?php 
$tagit = new modules\opsModule\models\tagit;
$tagit->__renderJS();
$tagit->__renderCSS();
?>
<!-- ckeditor placeholder -->
<div id="editor-container">
    <form action="/<?php echo $this->request->action->name ?>/note/<?php echo $this->edit ? "$note_id?": "?pid=$this->pid"?><?php echo zinux\kernel\security\security::__get_uri_hash_string(array("note", $this->edit ? $note_id: $this->pid, session_id(), \core\db\models\user::GetInstance()->user_id)); ?>" method="POST" name='note'>
        <input type="hidden" name="version" value="html" />
    <?php
        # forge default tag based on note's route to root pattern
        if(!strlen($tags)) { foreach($this->route as $folder) { if($folder->getItemID() === 0) continue; $tags = "$tags, {$folder->getItemTitle()}"; } }
        $tagit->__renderHTML($tags);
    ?>
    <?php if($this->edit) : ?>
        <input type="hidden" name="note_id" value="<?php echo $note_id ?>" />
    <?php endif; ?>
        <div id="editor-parent">
            <ol class="breadcrumb">
                <?php $count = 0; foreach($this->route as $folder) : $active = count($this->route) == ++$count; ?>
                    <li <?php echo $active?"class='active'":""?>><?php echo !$active?"<a href='/#!/d/{$folder->folder_id}.folders'>":"", $folder->folder_title, !$active?"</a>":""?></li>
                <?php endforeach;unset($count);?>
                <li class="pull-right no-bc-slash cd"><a href="#" onclick="change_path();return false;" data-toggle="tooltip" title="Change the path where the note will be saved.">Change</a></li>
            </ol>
            <div class="input-group pull-left" style="margin-top: -10px;">
                <input type="text" name="note_title"  id="editor-title" class="block input form-control" placeholder="Your note's title" value="<?php echo str_replace('"', "&quot;", $title) ?>" autofocus="" maxlength="300"/>
                <span class="input-group-btn">
                    <button onclick="save();" type="button" class="btn btn-default" style="border-bottom-left-radius: 0;border-top-left-radius: 0;" tabindex="-1" title="Save">
                        <span class="glyphicon glyphicon-hdd"></span> Save
                    </button>
                    <a href="<?php echo $this->edit && $note_id ? "/view/note/$note_id" : "/#!/d/{$this->pid}.notes" ?>" title="Discard" class="note-discard btn btn-warning" tabindex="-1" style="margin-left:10px;">
                        <span class="glyphicon glyphicon-trash"></span> Discard
                    </a>
                <a class="btn btn-success" onclick='tagit();return false;' tabindex="-1" style="margin-left:10px;" title="Tag this note">
                    <span class="glyphicon glyphicon-tags"></span> Tagit
                </a>
                </span>
                <div class="pull-right">
                    <div class="input-group inline">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1">
                              <span class="glyphicon glyphicon-cog"></span>  <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li class="divider hidden"></li>
                                <li title="Change to Ace editor"><a href="#/editor/change/to/ace?continue=<?php echo urlencode("/".$this->request->action->name."/note/".($this->edit? "$note_id?": "?pid=$this->pid").zinux\kernel\security\security::__get_uri_hash_string(array("note", $this->edit? $note_id: $this->pid, session_id(), \core\db\models\user::GetInstance()->user_id))); ?>" id="switch-editor"><span class="glyphicon glyphicon-credit-card"></span> Ace editor</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix" style="margin: 10px;"></div>
            <textarea id="editor" class="tinyMCE form-control hidden" id="editor-platform" tabindex="1" name="note_body" style="width: 100%;"><?php
                    (new \vendor\markdown\Ciconia\CiconiaInitializer())->Execute();
                    use Ciconia\Extension\Gfm;
                    $ciconia = new \Ciconia\Ciconia();
                    $ciconia->addExtension(new Gfm\FencedCodeBlockExtension());
                    $ciconia->addExtension(new Gfm\TaskListExtension());
                    $ciconia->addExtension(new Gfm\InlineStyleExtension());
                    $ciconia->addExtension(new Gfm\WhiteSpaceExtension());
                    $ciconia->addExtension(new Gfm\TableExtension());
                    $ciconia->addExtension(new Gfm\UrlAutoLinkExtension());
                    echo trim($ciconia->render($body));
                    ?></textarea>
        </div>
    </form>
</div>