<?php if(!isset($this->e)) throw new \zinux\kernel\exceptions\invalidArgumentException; ?>
<?php \zinux\kernel\utilities\debug::_var($this->e); ?>
<style>
    table tr td:first-child {font-weight: bold;}
</style>
<table class="table table-hover container">
    <thead>
        <tr>
            <th style="min-width: 200px;font-weight: bold">Label</th>
            <th>Info</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->e->to_array() as $key => $value) : $a_key =ucwords(implode(' ', explode("_", $key))); ?>
        <tr class="<?php echo $key ?>">
            <td><?php echo $a_key ?></td>
            <td><?php echo $value ? $value : "NONE-LOGGEDING"; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script src="/access/js/moment.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var $time_elem = $($(".created_at").children("td")[1]);
        $time_elem.html(moment($time_elem.text()).fromNow("lll") + " ago");
        console.log($time_elem);
//        var $edata = 
    });
</script>