<div id="explorer-template">
<?php if(count($this->route)): ?>
<ol class="breadcrumb">
<?php
    $dt = new modules\frameModule\models\directoryTree($this->request);
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route)); if(!$folder->folder_id) continue?>
        <li <?php echo $is_active?" class='active'":""?>>
            <?php 
                if(!$is_active)
                    echo "<a link-type='folder' class='table-nav-link' href='{$dt->getNavigationLink($folder)}' onclick='window.top.document.title = \"/ $folder->folder_title\";'>";
                echo $folder->folder_title;
                if(!$is_active)
                    echo "</a>";
            ?>
        </li>
<?php endforeach; ?>
</ol>
<script>
    (function(){
        $("#explorer-template ol.breadcrumb").prepend("<li "+($("#explorer-template ol.breadcrumb li.active").length?"":"class='active'")+">"+window.top.getAciveNavHtml()+"</li>");
    })(jQuery);
</script>
<?php endif; ?>
<?php
    $type = $this->request->type;
    $parent_id = $this->pid;
    $is_owner = $this->is_owner;
    $dt->plotOptions($type, $parent_id, $is_owner);
    $dt->plotHeadTypes($type, $parent_id);
    $dt->plotJS($type, $parent_id, $is_owner);
?>
</div>
<?php
    $dt->{"plot{$type}"}($this->items, $parent_id, $is_owner);
?>