<div id="explorer-template">
<ol class="breadcrumb"></ol>
<script>
    (function(){
        $("#explorer-template ol.breadcrumb").prepend("<li>"+window.top.getActiveNavHtml()+"</li>");
    })(jQuery);
</script>
<?php
    $type = $this->request->type;
    $parent_id = $this->pid;
    $is_owner = $this->is_owner;
    $dt = new modules\frameModule\models\directoryTree($this->request, modules\frameModule\models\directoryTree::TRASH);
    $dt->plotOptions($type, $parent_id, $is_owner);
    $dt->plotHeadTypes($type, $parent_id);
    $dt->plotJS($type, $parent_id, $is_owner);
?>
</div>
<?php
    $dt->{"plot{$type}"}($this->items, $parent_id, $is_owner);
?>