<div class="pull-left" id="exp-nav" style="width: 100%;margin: -10px">
    <h3>&nbsp;</h3>
    <ul class="nav nav-pills nav-stacked">
        <li class="active">
            <a id='root' user-data="" href="/frame/e" target="explorer-frame"><span class="glyphicon glyphicon-th-large"></span> Root</a>
        </li>
        <li>
            <a id='archives' user-data="!/archives" href='/archives' target="explorer-frame"><span class="glyphicon glyphicon-floppy-disk"></span> Archives</a>
        </li>
        <li>
            <a id='shared' user-data="!/shared" href='/shared' target="explorer-frame"><span class="glyphicon glyphicon-share-alt"></span> Shared</a>
        </li>
        <li>
            <a id='trashes' user-data="!/trashes" href='/trashes' target="explorer-frame"><span class="glyphicon glyphicon-trash"></span> Trashes</a>
        </li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("div#exp-nav ul.nav li a[target='explorer-frame']").click(function(){
            window.top.active_nav($(this).attr('id'));
            window.top.location.hash = $(this).attr('user-data');
        });
        window.top.active_nav = function(id) {
            $(window.top.document.getElementById('explorer-nav-frame')).contents().find("div#exp-nav ul.nav li a[target='explorer-frame']").parent().removeClass("active");
            $(window.top.document.getElementById('explorer-nav-frame')).contents().find("div#exp-nav ul.nav li a[target='explorer-frame']#"+id).parent().addClass("active");
        };
        window.top.getAciveNavHtml = function() {
            var $anh = $(window.top.document.getElementById('explorer-nav-frame')).contents().find("div#exp-nav ul.nav li a[target='explorer-frame']").clone();
            return $anh.removeAttr("user-data")
                    .removeAttr("target")
                        .wrap('<p/>').parent().html();
        };
        try {
            var uri = 'root';
            var postFix = '';
            if(window.location.hash.split('#!/')[1] !== undefined) {
                uri = window.location.hash.split('#!/')[1];
                if(uri.split("/").length)
                    uri = uri.split("/")[0];
            }
            switch(uri) {
                default:
                case "root":
                    switch(String(window.location.hash).toLowerCase()) {
                        case "#!/root":
                        case "#!/root/":
                            window.location.hash = '';
                        default:
                            window.location.hash = "!/"+window.location.hash.replace(/^(#!\/)(root(\/))?(.*)/gi, '$4');
                    }
                    uri = 'root';
                    postFix = window.location.hash.split('#!')[1];
                    break;
                case "archives":
                case "shared":
                case "trashes":
                    break;
            }
            window.top.active_nav(uri);
            window.top.document.getElementById('explorer-frame').src = $("div#exp-nav ul.nav li a#"+uri).attr('href') + postFix;
        } catch(e) {
            window.location.hash = '';
            window.top.document.getElementById('explorer-frame').src = $("div#exp-nav ul.nav li a#"+uri).attr('href');
        }
    });
</script>