<div class="pull-left" id="exp-nav" style="width: 100%;margin: -10px">
    <h3>&nbsp;</h3>
    <ul class="nav nav-pills nav-stacked">
        <li class="active">
            <a id='root' user-data="!/d/0.folders" href="/d/0.folders" target="explorer-frame"><span class="glyphicon glyphicon-th-large"></span> Root</a>
        </li>
        <li>
            <a id='archives' user-data="!/archives" href='/archives' target="explorer-frame"><span class="glyphicon glyphicon-floppy-disk"></span> Archives</a>
        </li>
        <li>
            <a id='shared' user-data="!/shared" href='/shared' target="explorer-frame"><span class="glyphicon glyphicon-share-alt"></span> Shared</a>
        </li>
        <li>
            <a id='trashes' user-data="!/trashes" href='/trashes' target="explorer-frame"><span class="glyphicon glyphicon-trash"></span> Trashes</a>
        </li>
    </ul>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("div#exp-nav ul.nav li a[target='explorer-frame']").click(function(){
            window.top.active_nav($(this).attr('id'));
            window.top.location.hash = $(this).attr('user-data');
            console.log(["u", $(this).attr('user-data')]);
        });
        window.top.update_nav = function(auto_redirect) {
            if(typeof(auto_redirect) === "undefined") auto_redirect = false;
            try {
                var uri = 'root';
                var defURI = "/d/0.folders";
                if(window.location.hash.length === 0) window.location.hash ="#!"+defURI;
                if(window.location.hash.split('#!')[1] !== undefined) {
                    var __uri = String(window.location.hash.split('#!/')[1]).split("/");
                    if(__uri.length && __uri[0].length)
                        uri = __uri[0];
                }
                switch(uri) {
                    default:
                        window.location.hash ="#!"+defURI;
                    case "d":
                    case "root":
                    case "frame":
                        uri = 'root';
                    case "shared":
                    case "trashes":
                    case "archives":
                        if(!window.location.hash.match(/^#\!/ig)) window.location.hash = "#!"+defURI;
                        var target = window.location.hash.split('#!')[1];
                        if(target.length === 0 || target === "/")
                            target = defURI;
                        window.top.active_nav(uri);
                        if(auto_redirect)
                            window.top.document.getElementById('explorer-frame').src = target;
                        break;
                }
            } catch(e) {
                window.top.open_errorModal("<span class='glyphicon glyphicon-remove'></span> "+e);
            }
        };
        window.top.update_nav(true);
    });
</script>