<ol class="breadcrumb">
<?php
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route)); if(!$folder->folder_id) continue; ?>
        <li <?php echo $is_active?" class='active'":""?>>
            <?php 
                if(!$is_active)
                    echo "<a link-type='folder' status='{$dt->getStatusBinary($folder)}' class='table-nav-link' href='{$dt->getNavigationLink($folder)}'>";
                echo $folder->folder_title;
                if(!$is_active)
                    echo "</a>";
            ?>
        </li>
<?php endforeach; ?>
</ol>
<script>
    (function(){
        $("#explorer-template ol.breadcrumb").prepend("<li>"+window.top.getActiveNavHtml()+"</li>");
<?php if(count($this->route)): ?>
        var removeBCByStatusPattern = function(pattern, break_pattern) {
            console.log(["pattern", pattern]);
            $("#explorer-template ol.breadcrumb li a").each(function(index, elem){
                var status = $(elem).attr('status');
                if(typeof(status) === "undefined") return;
                console.log(["elem", $(elem).text().trim(), "status", status]);
                if(status.match(new RegExp(pattern, "ig"))) {
                    console.log("Matched");
                    $(elem).parent().remove(); 
                }
                if(status.match(new RegExp(break_pattern, "ig"))) return false;
            });
        };
        switch(window.top.getActiveType()) {
            case "root": /* NOP in root type */ break;
            case "archives":
                removeBCByStatusPattern("\\d0\d", "\\d1\\d");
                break;
            case "trashes":
                removeBCByStatusPattern("\\d\\d0", "\\d\\d1");
                break;
            case "shared":
                removeBCByStatusPattern("0\\d\\d", "1\\d\\d");
                break;
        }
<?php endif; ?>
    })(jQuery);
</script>