<ol class="breadcrumb">
<?php $active_folder = NULL; ?>
<?php
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route)); if(!$folder->folder_id) continue; ?>
        <li <?php echo $is_active?" class='active'":""?>>
            <?php 
                if(!$is_active)
                    echo "<a link-type='folder' status='{$dt->getStatusBinary($folder)}' class='table-nav-link' href='{$dt->getNavigationLink($folder)}'>";
                echo "<span hash-link='{$dt->getNavigationLink($folder)}'>",$folder->folder_title, "</span>";
                if(!$is_active)
                    echo "</a>";
                else $active_folder = $folder;
            ?>
        </li>
<?php endforeach; ?>
</ol>
<script>
    (function(){
<?php
    $pattern = array();
    $type = "root";
    switch($dt->tree_type) {
            case \modules\frameModule\models\directoryTree::REGULAR: /* NOP in root type */ break;
            case \modules\frameModule\models\directoryTree::ARCHIVE:
                $type = "archives";
                $pattern = array('\\\d0\\\d', '\\\d1\\\d');
                break;
            case \modules\frameModule\models\directoryTree::SHARED:
                $type = 'trashes';
                $pattern = array('\\\d\\\d0', '\\\d\\\d1');
                break;
            case \modules\frameModule\models\directoryTree::TRASH;
                $type = 'shares';
                $pattern = array('0\\\d\\\d', '1\\\d\\\d');
                break;
        }
?>
        window.top.active_nav('<?php echo $type ?>');
        $("#explorer-template ol.breadcrumb").prepend("<li>"+$(window.top.getActiveNavHtml()).wrapInner("<span hash-link='"+window.top.getActiveTypeLink()+"'></span>").wrap("<p>").parent().html()+"</li>");
        if($("#explorer-template ol.breadcrumb li.active").length === 0) {
            $("#explorer-template ol.breadcrumb li:last").addClass("active");
            if($("#explorer-template ol.breadcrumb li:last a").length !== 0) {
                $("#explorer-template ol.breadcrumb li:last").html($("#explorer-template ol.breadcrumb li:last a").html());  
            }
        }
<?php if(count($this->route)): ?>
        var removeBCByStatusPattern = function(pattern, break_pattern) {
            $("#explorer-template ol.breadcrumb li a[link-type='folder']").each(function(index, elem){
                var status = $(elem).attr('status');
                if(typeof(status) === "undefined") return;
                if(status.match(new RegExp(pattern, "ig"))) {
                    $(elem).parent().remove(); 
                }
                if(status.match(new RegExp(break_pattern, "ig"))) return false;
            });
        };
<?php if(count($pattern)): ?>
        removeBCByStatusPattern(<?php echo "'$pattern[0]', '$pattern[1]'"; ?>);
<?php endif; ?>
<?php endif; ?>
    })(jQuery);
</script>