<ol class="breadcrumb">
<?php $active_folder = NULL; ?>
<?php
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route)); if(!$folder->folder_id) continue; ?>
        <li <?php echo $is_active?" class='active'":""?>>
            <?php 
                if(!$is_active)
                    echo "<a link-type='folder' status='{$dt->getStatusBinary($folder)}' class='table-nav-link' href='{$dt->getNavigationLink($folder)}'>";
                echo "<span hash-link='{$dt->getNavigationLink($folder)}'>",$folder->folder_title, "</span>";
                if(!$is_active)
                    echo "</a>";
                else $active_folder = $folder;
            ?>
        </li>
<?php endforeach; ?>
</ol>
<script>
    (function(){
        $("#explorer-template ol.breadcrumb").prepend("<li>"+$(window.top.getActiveNavHtml()).wrapInner("<span hash-link='"+window.top.getActiveTypeLink()+"'></span>").wrap("<p>").parent().html()+"</li>");
        if($("#explorer-template ol.breadcrumb li.active").length === 0) {
            $("#explorer-template ol.breadcrumb li:last").addClass("active");
            if($("#explorer-template ol.breadcrumb li:last a").length !== 0) {
                $("#explorer-template ol.breadcrumb li:last").html($("#explorer-template ol.breadcrumb li:last a").html());  
            }
        }
<?php if(count($this->route)): ?>
        var removeBCByStatusPattern = function(pattern, break_pattern) {
            $("#explorer-template ol.breadcrumb li a[link-type='folder']").each(function(index, elem){
                var status = $(elem).attr('status');
                if(typeof(status) === "undefined") return;
                if(status.match(new RegExp(pattern, "ig"))) {
                    $(elem).parent().remove(); 
                }
                if(status.match(new RegExp(break_pattern, "ig"))) return false;
            });
        };
        switch(window.top.getActiveType()) {
            case "root": /* NOP in root type */ break;
            case "archives":
                removeBCByStatusPattern("\\d0\\d", "\\d1\\d");
                break;
            case "trashes":
                removeBCByStatusPattern("\\d\\d0", "\\d\\d1");
                break;
            case "shared":
                removeBCByStatusPattern("0\\d\\d", "1\\d\\d");
                break;
        }
<?php endif; ?>
    })(jQuery);
</script>