<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div>
            <a href="/auth/signin">Signin</a> | 
            <a href="/auth/signout">Signout</a> | 
            <a href="/auth/signup">Signup</a> | 
            <a href="/auth/clear">Clear All</a> | 
            <a href="/">Home</a>
<?php if(\core\db\models\user::IsSignedin()) :?>
            <a href="/messages/new/<?php echo \core\db\models\user::GetInstance()->user_id ?>?<?php 
                echo \zinux\kernel\security\security::GetHashString(array(core\db\models\user::GetInstance()->user_id, core\db\models\user::GetInstance()->user_id, session_id())) 
            ?>" style="float:right">Send Message</a>
<?php endif; ?>
        </div>
        <hr />
        <?php echo $this->content; ?>
    </body>
</html>