<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>
    </head>
    <body>
        <div>
            <a href="/auth/signin">Signin</a> | 
            <a href="/auth/signout">Signout</a> | 
            <a href="/auth/signup">Signup</a> | 
            <a href="/auth/clear">Clear All</a> | 
            <a href="/">Home</a>
        </div>
        <?php echo $this->content; ?>
    </body>
</html>