<style type="text/css">
    .tag-sug-block{
        border-radius: 3px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
        -moz-user-select: none; 
        -khtml-user-select: none; 
        -webkit-user-select: none; 
        -o-user-select: none; 
    }
    .tag-sug-block{
        display: table;
        margin: 10px;
        padding: 10px;
        height: 34px;
        min-width: 50px;
        border: 1px solid #000;
        word-break: break-all;
        float: left;
    }
    .tag-sug-value { font-weight: bold; }
    .tag-sug-block:hover{
        background-color: #0088cc;
        color: #fff;
        cursor: pointer;
    }
</style>
<div style="width: 100%">
    <div class="tag-sug-block">Just use `<span class='tag-sug-value'><?php echo $this->origin_term ?></span>`</div>
    <?php foreach($this->tags as $tag): ?>
    <div class="tag-sug-block"><div class="tag-sug-value"><?php echo $tag->tag_value; ?></div></div>
    <?php endforeach; ?>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    $(function(){
        $(".tag-sug-block").click(function(){
            var function_exists = function(func_name) {
              if (typeof func_name === 'string') {
                func_name = this.window[func_name];
              }
              return typeof func_name === 'function';
            };
            if(!function_exists("submit_tag")) {
                alert("Sorry, Wrong configuration! Unable to submit the tag. if it happens there is somthing wrong with site, please contact us.\nYou can just press ENTER/RETURN key to submit your tag manually. :(");
                return;
            }
            submit_tag($(this).children(".tag-sug-value:first").text());
        });
    });
</script>