<style type="text/css">
    .tag-sug-block{
        border-radius: 3px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
    }
    .tag-sug-block{
        display: table;
        margin: 10px;
        padding: 10px;
        height: 34px;
        min-width: 50px;
        font-weight: bold;
        border: 1px solid #000;
        word-break: break-all;
    }
    .tag-sug-block:hover{
        background-color: #0088cc;
        color: #fff;
        cursor: pointer;
    }
</style>
<!--
 The \modules\opsModule\views\view\fetch\tagsView
 @by Zinux Generator <b.g.dariush@gmail.com>
 -->
<p>
    A view for '<b>\modules\opsModule\controllers\fetchController::tagsAction()</b>'<br />
    Location: '<b>/var/www/toratan/modules/opsModule/views/view/fetch/tagsView.phtml</b>'
</p>