<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="/access/js/jquery-1.11.1.min.js"></script>
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
        <link rel="shortcut icon" href="/favicon.ico">
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
</html>