<?php $glayout = new \modules\defaultModule\views\layout\genLayoutHeader($this); ?>
<?php $glayout->render_header(); ?>
        <div class="container" style="margin-top:10px;">
            <div class="row sign">
                  <div class="col-lg-5 col-sm-3 hidden-xs">
                      <h4>What is toratan?</h4>
                      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

                      <h4>Features</h4>
                      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
                  </div>
                  <div class="col-lg-7 col-sm-9" style='
                       padding: 10px!important'>
                        <?php echo $this->content; ?>
                  </div>
            </div>
        </div> <!-- /container -->
<?php $glayout->render_footer(); ?>