<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
    </head>
    <body>
    </body>
</html>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sign up page">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            /* Space out content a bit */
            body {
              padding-top: 20px;
              padding-bottom: 20px;
            }

            /* Custom page header */
            .header {
              border-bottom: 1px solid #e5e5e5;
            }
            /* Make the masthead heading the same height as the navigation */
            .header h3 {
              margin-top: 0;
              margin-bottom: 0;
              line-height: 40px;
              padding-bottom: 19px;
            }

            /* Custom page footer */
            .footer {
              padding-top: 19px;
              color: #777;
              border-top: 1px solid #e5e5e5;
            }

            /* Customize container */
            /*@media (min-width: 768px) {
              .container {
                max-width: 930px;
              }
            }*/

            /* Supporting sign content */
            .sign {
              margin: 40px 0;
            }
            .sign p + h4 {
              margin-top: 28px;
            }

            /* Responsive: Portrait tablets and up */
            @media screen and (min-width: 768px) {
              /* Remove the padding we set earlier */
              .header,
              .sign,
              .footer {
                padding-left: 0;
                padding-right: 0;
              }
              /* Space out the masthead */
              .header {
                margin-bottom: 30px;
              }
            }
            .form-sign {
                padding:10px;
                padding-left: 45px;
                padding-right: 45px;
                margin: 0 auto;
            }
            .form-sign .form-sign-heading,
            .form-sign .checkbox {
                margin-bottom: 10px;
            }
            .form-sign .checkbox {
                font-weight: normal;
            }
            .form-sign .form-control {
                position: relative;
                font-size: 16px;
                height: auto;
                padding: 10px;
                -webkit-box-sizing: border-box;
               -moz-box-sizing: border-box;
                box-sizing: border-box;
                width: 100%;
            }
            .form-sign .form-control:focus {
                z-index: 2;
            }
            .form-sign input[type="password"],
            .form-sign input[type="text"] {
                margin-bottom: -1px;
                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;
            }
            .form-sign input[type="text"] :last-of-type,
            .form-sign input[type="password"]:last-of-type{
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li><a href="index.html#">Home</a></li>
                    <li><a href="/signin">Signin</a></li>
                </ul>
                <h3 class="text-muted"><?php echo $this->GetTitle();?></h3>
            </div>

            <div class="row sign">
                  <div class="col-lg-5">
                      <h4>What is toratan?</h4>
                      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

                      <h4>Features</h4>
                      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>
                  </div>

                  <div class="col-lg-7" style='background-color: #efefef;border: 1px solid #e4e4e4;padding: 10px!important'>
                        <?php echo $this->content; ?>
                  </div>
            </div>
        <div class="footer"></div>
        </div> <!-- /container -->
  </body>
</html>
