<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<?php echo $this->GetTitle(); ?>">
        <?php $this->renderTitle(); ?>
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
        <link rel="shortcut icon" href="/favicon.ico">
        <style>
            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }
            .form
            {  
                margin-top:4%;
            }
            .form-signin {
                max-width: 430px;
                padding: 45px;
                margin: 0 auto;
                background-color: #efefef;
                border: 1px solid #e4e4e4;
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin .checkbox {
                font-weight: normal;
            }
            .form-signin .form-control {
                position: relative;
                font-size: 16px;
                height: auto;
                padding: 10px;
                -webkit-box-sizing: border-box;
               -moz-box-sizing: border-box;
                box-sizing: border-box;
            }
            .form-signin .form-control:focus {
                z-index: 2;
            }
            .form-signin input[type="text"] {
                margin-bottom: -1px;
                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;
            }
            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }

            /* Responsive: Portrait tablets and up */
            @media screen and (min-width: 768px) {
              /* Remove the padding we set earlier */
              .header,
              .sign,
              .footer {
                padding-left: 0;
                padding-right: 0;
              }
              /* Space out the masthead */
              .header {
                margin-bottom: 30px;
              }
            }
            /* Space out content a bit */
            body {
              padding-top: 20px;
              padding-bottom: 20px;
            }

            /* Custom page header */
            .header {
              border-bottom: 1px solid #e5e5e5;
            }
            /* Make the masthead heading the same height as the navigation */
            .header h3 {
              margin-top: 0;
              margin-bottom: 0;
              line-height: 40px;
              padding-bottom: 19px;
            }

            /* Custom page footer */
            .footer {
              padding-top: 19px;
              color: #777;
              border-top: 1px solid #e5e5e5;
            }
        </style>
        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
          <div class="container">
              <div class="header">
                  <ul class="nav nav-pills pull-right">
                      <li><a href="/">Home</a></li>
                      <li><a href="/signup">Signup</a></li>
                  </ul>
                  <h3 class="text-muted"><?php echo $this->GetTitle(); ?></h3>
              </div>
              <div class="form">
                  <?php echo $this->content; ?>
              </div>
          </div>
      </body>
</html>