<style>
    td{padding: 10px;min-width: 10%;}
    td .last{border-bottom: 1px solid #e6e6e6}
</style>
<hr />
<table>
    <thead>
        <tr>
            <td>User ID</td>
            <td>Username</td>
            <td>Email</td>
            <td>Password</td>
            <td>Created At</td>
            <td class="last">Updated At</td>
        </tr>
    </thead>
    <tbody>
<?php
        foreach($this->users as $user)
        {
?>
        <tr>
            <td><?php echo $user->user_id ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->password ?></td>
            <td><?php echo $user->created_at ?></td>
            <td class="last"><?php echo $user->updated_at ?></td>
        </tr>
<?php
        }
?>
    </tbody>
</table>