<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sign up page">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    <body>
        <script>
                $(document).ready(function()
                {
                    $("div#editor").show();
                    var editor = ace.edit("editor");
                    editor.setTheme("ace/theme/monokai");
                    editor.setTheme("ace/theme/twilight");
                    editor.getSession().setMode("ace/mode/markdown");
                    editor.getSession().setTabSize(4);
                    editor.commands.addCommand({
                        name: 'save',
                        bindKey: {win: 'Ctrl-S',  mac: 'Command-S'},
                        exec: save
                    });
                });
                function save(editor) 
                {
                    $("form[name='note'] input[name='note_title']").val($("#editor-title").val());
                    $("form[name='note'] textarea[name='note_body']").html(editor.getValue());
                    $("form[name='note']").submit();
                }        
        </script>
        <style type="text/css" media="screen">
            #editor { 
                position: fixed;
                top:0;
                right: 0;
                bottom: 0;
                left: 0;
            }
        </style>
        <div id="editor" style="display: none" ><?php echo isset($this->values['note_body'])?$this->values['note_body']:"Your note's body here." ?></div>
        <script src="/access/rte/ace/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
        <form action="/ops/new/note/?<?php echo $this->request->params["get"]?>" method="POST" name='note'>
            <input type="text" name="note_title" maxlength="250" value="<?php echo isset($this->values['note_title'])?$this->values['note_title']:"" ?>" required="required"/><br />
            <textarea rows="10" cols="80" name="note_body" ><?php echo isset($this->values['note_body'])?$this->values['note_body']:"" ?></textarea>
            <input type="submit" value="Create" />
        </form>
  </body>
</html>
    