<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <noscript>
            <meta http-equiv="Refresh" content="10; URL=<?php echo $this->request->getURI() ?>?&ui=html">
        </noscript>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="" style="width: 100%;">
            <div class="" >
                <?php
                    $mp = new core\utiles\messagePipe;
                    $msg = $mp->read();
                    if($msg)
                    {
                        \core\ui\html\alert::Cout($msg);
                    }
                ?>
                <?php echo $this->content?>
            </div>
        </div> <!-- /container -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
        <noscript style="z-index: 2000000; position: absolute; width:  100%; top:0;">
            <?php \core\ui\html\alert::Cout("Your browser javascript is not enabled, the browser will redirect to html version!!", \core\ui\html\alert::ALERT_DANGER); ?>
        </noscript>
  </body>
</html>
