<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
    </head>
    <body>
    </body>
</html>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sign up page">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <link rel="shortcut icon" href="/favicon.ico">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            /* Custom page footer */
            .footer {
              margin-top: 19px;
              color: #777;
              border-top: 1px solid #e5e5e5;
            }
            .container{
                width: 100%;
                padding:0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
            <div class="footer"></div>
        </div> <!-- /container -->
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
  </body>
</html>
