<?php if(!@$this->view->profile) throw new \zinux\kernel\exceptions\invalidArgumentException("Not profile instance provided...."); ?>
<?php $is_profile_owner = @$this->view->is_owner;  ?>
<?php $is_preview_mode = @$this->view->preview_mode;  ?>
<?php $active_type = strtolower(@$this->view->active_type);
    switch($active_type) {
        case "about": case "posts": break;
        default: $active_type = "about";
    }
?>
<?php $profile = \core\db\models\profile::getInstance($this->view->profile->user_id, 0, 0); ?>
<?php $cover_img = $profile->getSetting("/profile/cover/image"); ?>
<?php $cover_info = $profile->getSetting("/profile/cover/info"); ?>
<?php $glayout = new \modules\defaultModule\views\layout\genLayoutHeader($this); ?>
<?php $glayout->render_header(); ?>
<style type="text/css">
    #cover-photo img{
        max-height: 410px;
        width: 100%;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
        border-bottom: 0;
    }
    .navbar-static-top{border-left: 1px solid #DDDDDD; border-right: 1px solid #DDDDDD; margin-top:-10px;}
</style>
<link rel="stylesheet" href="/access/css/mosaic.css" type="text/css" media="screen">
<style type="text/css">
    .icenter-block { float: none; display: -moz-inline-stack; display:inline-block; vertical-align:top; *display:inline; background-color:transparent; }
    .loading-bar {width: 0;height: 3px;display: none;}
</style>
<div class="container" style='padding: 0'>
<?php if($cover_img): ?>
    <div id="cover-photo">
        <div class='mosaic-block bottom-bar icenter-block'>
        <?php if($is_profile_owner) : ?>
            <a href="/profile/cover" class="mosaic-overlay" id="change-cover" style="cursor:pointer;display: inline; left: 0px; bottom: -40px;" title="Change Cover">
                <div class="details text-center" style="margin-top: 0;">
                    <h1><span class="glyphicon glyphicon-picture"></span><br /><b>Change Cover</b></h1>
                </div>
            </a>
        <?php endif ; ?>
            <div class="cover-img">
                <img src="<?php echo $cover_img; ?>" class="image imageblock img-responsive img-thumbnail"/>
            </div>
        </div>
    </div>
<?php else: ?>
    <div style="margin-top: 10px;"></div>
<?php endif; ?>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li class="<?php echo $active_type === "about" ? "active" : "" ?>">
                    <a href="/profile/<?php echo $is_preview_mode?"preview/":""?>about">
                        <span class="glyphicon glyphicon-map-marker"></span> <b>About</b>
                    </a>
                </li>
                <li class="<?php echo $active_type === "posts" ? "active" : "" ?>">
                    <a href="/profile/<?php echo $is_preview_mode?"preview/":""?>posts">
                        <span class="glyphicon glyphicon-book"></span> <b>Posts</b>
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 0px;">
<?php if($cover_info && !$is_profile_owner): ?>
                <li>
                    <a style="cursor: pointer" id="about-cover"><span class="glyphicon glyphicon-info-sign"></span> About Cover</a>
                </li>
<?php endif; ?>
<?php if(!$cover_img && $is_profile_owner): ?>
                <li>
                    <a href="/profile/cover"><span class="glyphicon glyphicon-plus"></span> Cover Photo</a>
                </li>
<?php endif; ?>
<?php if(!$is_profile_owner): ?>
                <li title="Send Message">
                    <a href="<?php echo $is_preview_mode?"#": "#message"?>"><span class="glyphicon glyphicon-envelope"></span> Message</a>
                </li>
                <li title="Follow">
                    <a href="<?php echo $is_preview_mode?"#": "#follow"?>"><span class="glyphicon glyphicon-plus"></span> Follow</a>
                </li>
<?php elseif($active_type === "about"): ?>
                <li title='View your public profile'>
                    <a href='/profile/preview'><span class='glyphicon glyphicon-eye-open'></span> Preview</a>
                </li>
<?php endif; ?>
<?php if($is_preview_mode): ?>
                <li title='Go back to your profile' class="active">
                    <a href='/profile' target=""><span class='glyphicon glyphicon-eye-close'></span> Exit Preview</a>
                </li>
<?php endif;  ?>
            </ul>
        </div>
        <div class="loading-bar"></div>
    </nav>
    <div class="container">
        <?php echo $this->content?>
    </div>
</div> <!-- /container -->
<script type="text/javascript">
    (function(){
        $("a#about-cover").click(function(){
            window.open_infoModal(<?php echo json_encode("<center>$cover_info</center>") ?>);
        });
<?php if($is_profile_owner): ?>
        window.load_bar = function(is_launching) {
            if(typeof(is_launching) === "undefined") is_launching = true;
            window.loader_started = is_launching;
            if(!window.loader_started) return;
            var go_time = 1000;
            var back_time = 1000;
            function loader_go() {
                $( ".loading-bar" )
                        .css({width: 0, "margin-left": 0, float: "left", "background-color": "#5ea5c9" })
                        .show()
                        .animate({ "width": "+=100%" }, go_time, function(){ setTimeout(loader_back, 100); });
            }
             function loader_back(){
                $( ".loading-bar" )
                        .css({width: "100%", "margin-left": 0, float: "right", "background-color": "#5ea5c9" })
                        .animate({ "width": "0" }, back_time, function(){  if(window.loader_started) setTimeout(loader_go, 100); else { $( ".loading-bar" ).hide(); delete window.loader_started; } }); 
            };
            loader_go();
        };
<?php endif; ?>
    })(jQuery);
</script>
<?php $glayout->render_footer(); ?>