<?php if(!@$this->view->profile) throw new \zinux\kernel\exceptions\invalidArgumentException("Not profile instance provided...."); ?>
<?php $active_type = strtolower(@$this->view->active_type);
    switch($active_type) {
        case "about": case "posts": break;
        default: $active_type = "about";
    }
    $render_avatar = function(zinux\kernel\view\baseView $view) {
         list($avatar_uri , $def_avatar) = \core\ui\html\avatar::get_avatar_link($view->profile->user_id);
        $is_profile_owner = (@\core\db\models\user::GetInstance()->user_id == $view->profile->user_id); 
?>
        <div class="mosaic-block bottom-bar img-thumbnail" style="background-color: transparent">
        <?php if($is_profile_owner) : ?>
            <a href="/profile/avatar"  class="mosaic-overlay" style="display: inline; left: 0px; bottom: -45px;">
                <div class="details text-center ">
                    <h1><span class="glyphicon glyphicon-picture"></span><br /><b>Change Avatar</b></h1>
                </div>
            </a>
        <?php endif ; ?>
            <a href="/profile/avatar/view/<?php echo $view->profile->user_id, "?", \zinux\kernel\security\security::GetHashString(array($view->profile->user_id)) ?>" target="__blank">
                <img id="thumbnail" width="200" height="200" class='col-lg-12 img-responsive img-thumbnail' src="<?php echo $avatar_uri ?>" onerror="this.src='<?php echo $def_avatar ?>';"  />
            </a>
        </div>
<?php
    }
?>
<?php $glayout = new \modules\defaultModule\views\layout\genLayoutHeader($this); ?>
<?php $glayout->render_header(); ?>
<div class="container-fluid" style="width: 77%">
    <div id="cover-photo">
        <img src="<?php echo '/access/img/upload/cover/bc164218f758cd3a59cd5f1cb98fd0563a327f69_2.jpg'; ?>" class="image imageblock img-responsive img-thumbnail" />
    </div>
    <link rel="stylesheet" href="/access/css/mosaic.css" type="text/css" media="screen">
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <ul class="nav navbar-nav ">
                <li class="<?php echo $active_type === "about" ? "active" : "" ?>">
                    <a href="/profile/about">
                        <b>About</b>
                    </a>
                </li>
                <li class="<?php echo $active_type === "posts" ? "active" : "" ?>">
                    <a href="/profile/posts">
                        <b>Posts</b>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <style type="text/css">
        #profile-table td{ padding-right: 10px; }
    </style>
    <div class="container">
        <div class="row">
            <?php if($active_type === "about") : ?>
            <div class="pull-left col-md-3" style="padding-bottom: 10px;">
                <?php $render_avatar($this->view); ?>
            </div>
            <?php endif; ?>
            <div class="pull-left col-md-9">
                <?php echo $this->content?>
            </div>
        </div>
    </div>
</div> <!-- /container -->
<?php $glayout->render_footer(); ?>
<?php unset($render_avatar); ?>