<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <link rel="shortcut icon" href="/favicon.ico">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            /* Space out content a bit */
            body {
              padding-top: 0;
              padding-bottom: 0;
            }

            /* Custom page header */
            .header {
              border-bottom: 1px solid #e5e5e5;
            }

            /* Custom page footer */
            .footer {
              padding-top: 1%;
              color: #777;
              border-top: 1px solid #e5e5e5;
              clear: both;
            }

            /* Responsive: Portrait tablets and up */
            @media screen and (min-width: 768px) {
              /* Remove the padding we set earlier */
              .header,
              .tor,
              .footer {
                padding-left: 0;
                padding-right: 0;
              }
              /* Space out the masthead */
              .header {
                margin-bottom: 1%;
              }
            }
        </style>
    </head>
    <body>
        <div class="container" style="width: 100%;">
            <div>
                <?php
                    $mp = new core\utiles\messagePipe;
                    $msg = $mp->read();
                    if($msg)
                    {
                        \core\ui\html\alert::Tout($msg);
                    }
                ?>
                <?php echo $this->content?>
            </div>
        </div> <!-- /container -->
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
  </body>
</html>
