<?php $gauth = new modules\authModule\models\gAuth(); ?>
<div class="">
    <div  class="googleplus-container">
        <a href="<?php echo $gauth->getAuthURI() ?>" class="btn btn-danger" id="gauth" style="padding-top: 0;padding-bottom: 0;height: 40px" >
            <span class="sicon fa fa-google-plus"></span> 
            <span class="stext">Sign with Google</span>
        </a>
    </div> 
</div>
<style type="text/css">
    .googleplus-container span{color:white;font-weight: bold;}
    .sicon{font-size: x-large; padding-right: 10px; border-right:1px solid #a02b29;height: 39px;padding-top: 10px;float: left}
    .stext {width: 200px;padding:10px;float: right}
</style>
