<div class="container" style="width: 50%;">
    <?php
        $mp = new core\utiles\messagePipe("recovery");
        $message = $mp->read();
        if($message)
            \core\ui\html\alert::Tout($message, \core\ui\html\alert::PIPE_NONE, 0);
    ?>
    <?php if(count(@$this->errors)) : ?>
    <?php foreach($this->errors as $error) \core\ui\html\alert::Tout($error, \core\ui\html\alert::PIPE_DANGER); ?>
    <?php endif; ?>
    <form class="form-signin" action="/auth/recovery?<?php echo \zinux\kernel\security\security::__get_uri_hash_string(array(session_id(), "r3c0veRI"))?>" method="post"  role="form" style="padding-top: 10px;">
        <input type="text" class="form-control" placeholder="Email address" name="email"  style="margin-bottom: 10px;" required autofocus>
        <?php (new \vendor\recaptcha\recaptcha)->__render_js(); ?>
        <input type="submit" class="btn btn-lg btn-primary pull-right" id="submit-btn" value="Send recovery link" style="margin-top: 10px;"/>
        <div class="clearfix" />
    </form>
</div>
<style type="text/css">
    #recaptcha_table {width: 100%;}
</style>