<?php $u = $this->user; ?>
<?php $p =\core\db\models\profile::getInstance($u->user_id); ?>
<html>
    <body>
        <table bgcolor="#f1f1f1" width="100%" height="100%" align="center" style="border-collapse:collapse" border="0" cellspacing="0" cellpadding="0">
            <tbody>
                <tr align="center">
                    <td valign="top">
                        <table bgcolor="#f1f1f1" height="60" style="border-collapse:collapse" border="0" cellspacing="0" cellpadding="0">
                            <tbody>
                                <tr valign="middle" height="40">
                                    <td width="9"></td>
                                    <td width="10"></td>
                                    <td width="10"></td>
                                </tr>
                            </tbody>
                        </table>
                        <table border="1" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="text-align:left">
                            <tbody>
                                <tr>
                                    <td height="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                </tr>
                                <tr>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                    <td width="568" valign="top" style="font-size:83%;border-top:none;border-bottom:none;border-left:none;border-right:none;font-size:13px;font-family:arial,sans-serif;color:#222222;line-height:18px">
                                        Hi <?php echo $p->get_RealName_or_Username(); ?>,
                                        <br>
                                        <br>
                                        The password for your Toratan Account - <a href="mailto:b.dariush.h@gmail.com" target="_blank">b.dariush.h@gmail.com</a> - was recently changed.
                                        <br>
                                        If you made this change, you don't need to do anything more.
                                        <br>
                                        <br>
                                        If you didn't change your password, your account might have been hijacked. To get back into your account, you'll need to reset your password.
                                        <br>
                                        <br>
                                        <a href="https://accounts.google.com/RecoverAccount?fpOnly=1&amp;source=ancpse&amp;Email=b.dariush.h@gmail.com" style="text-align:center;font-size:11px;font-family:arial,sans-serif;color:white;font-weight:bold;border-color:#3079ed;background-color:#4d90fe;background-image:linear-gradient(top,#4d90fe,#4787ed);text-decoration:none;display:inline-block;min-height:27px;padding-left:8px;padding-right:8px;line-height:27px;border-radius:2px;border-width:1px" target="_blank">
                                        <span style="color:white">
                                        Reset password
                                        </span>
                                        </a>
                                        <br>
                                        <br>
                                        Sincerely,<br>
                                        The Google Accounts team
                                    </td>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                </tr>
                                <tr>
                                    <td height="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                </tr>
                                <tr>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none"></td>
                                    <td width="568" style="font-size:11px;font-family:arial,sans-serif;color:#777777;border-top:none;border-bottom:none;border-left:none;border-right:none">
                                        This email can't receive replies. For more information, visit the <a href="https://support.google.com/accounts/bin/answer.py?answer=1628875" style="text-decoration:none;color:#4d90fe" target="_blank"><span style="color:#4d90fe">Google Accounts Help Center</span></a>.
                                    </td>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none"></td>
                                </tr>
                                <tr>
                                    <td height="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                </tr>
                                <tr>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none"></td>
                                    <td width="568" style="font-size:11px;font-family:arial,sans-serif;color:#777777;border-top:none;border-bottom:none;border-left:none;border-right:none">
                                        If <a href="mailto:b.dariush.h@gmail.com" target="_blank">b.dariush.h@gmail.com</a> isn't your Google Account, <a href="https://accounts.google.com/AccountDisavow?adt=AOX8kipoMknf3ZrVqR7YfrZHPsjVJVMx71IN2FyP94wj8TySnmV11qbn1LtX2UjMaiY" target="_blank">click here</a> to disconnect your email address from this account.
                                    </td>
                                    <td width="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none"></td>
                                </tr>
                                <tr>
                                    <td height="15" style="border-top:none;border-bottom:none;border-left:none;border-right:none">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table bgcolor="#f1f1f1" height="80" style="text-align:left">
                            <tbody>
                                <tr valign="middle">
                                    <td style="font-size:11px;font-family:arial,sans-serif;color:#777777">
                                        You received this mandatory email service announcement to update you about important changes to your Google product or account.
                                        <br>
                                        <br>
                                        <div style="direction:ltr">
                                            © 2014 Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>