<style type="text/css">
    .form-signin {width: 420px;padding: 15px;margin: 10px auto;background-color: #efefef;border: 1px solid #e4e4e4;}
    .form-signin .form-control { position: relative; height: auto; -webkit-box-sizing: border-box; -moz-box-sizing: border-box;box-sizing: border-box; padding: 10px;font-size: 16px;}
    .form-signin .form-control:focus {z-index: 2;}
</style>
<form class="form-signin" action="/auth/signin" method="post"  role="form">
    <input type="hidden" name="continue" value="<?php echo $this->continue; ?>" />
    <?php if(count($this->errors)) : ?>
        <ul style="padding:10px;padding-left: 0px;font-weight: bold;" class="list-unstyled">
        <?php foreach ($this->errors as $error) : ?>
            <li class='text-danger'>&nbsp<?php echo $error ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <input type="text" class="form-control" placeholder="Username or Email address" name="username"  required autofocus>
    <input type="password" class="form-control" placeholder="Password"  name ="password" required>
    <label class="checkbox" style="margin-left: 20px;">
        <input type="checkbox" name="remember-me" checked> Stady sign in
    </label>
    <div class='form-group' style="margin: 0px;">
        <label for="submit-btn" class="control-label" style="padding-top:4%;"><a href="/recovery" class="pull-left" tabindex="-1">Recover your account</a></label>
        <div class="pull-right">
            <button class="btn btn-lg btn-primary " type="submit" id="submit-btn">Sign in</button>
        </div>
    </div>
    <div class='clearfix'></div>
    <div class="form-group" style="padding:3%;border-top: 2px solid #aaa;margin-top:10px;">
        <?php $this->RenderPartial("network_accounts"); ?>
    </div>
</form>