<style>
    input{display: block}
</style>
<form action="/auth/signup" method="post">
    <input type="text" name="username" placeholder="Your username" />
    <input type="text" name="email" placeholder="Email address" />
    <input type="text" name="password" placeholder="Password" />
    <input type="text" name="conf-password" placeholder="Confirm Password" />
    <input type="submit" value="Signup" />
</form>