<ol style="color:red;">
<?php foreach ($this->errors as $error) : ?>
    <li><?php echo $error ?></li>
<?php endforeach; ?>
</ol>
<form action="/auth/signin" method="post" role="form">
    <input type="hidden" name="continue" value="<?php echo $this->continue; ?>" />
    <div class="form-group">
        <label for="username">Username or Email</label>
        <input type="text" name="username" class="form-control" id="username" placeholder="Enter your username or email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name ="password" class="form-control" id="password" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-default">Sign in</button>
</form>