<form class="form-signin" action="/auth/signin" method="post"  role="form">
    <input type="hidden" name="continue" value="<?php echo $this->continue; ?>" />
    <ul style="color:red;font-variant: small-caps;padding:10px;padding-left: 0;font-weight: bold" class="list-unstyled">
    <?php foreach ($this->errors as $error) : ?>
        <li>&gt;&nbsp<?php echo $error ?></li>
    <?php endforeach; ?>
    </ul>
    <input type="text" class="form-control" placeholder="Username or Email address" name="username"  required autofocus>
    <input type="password" class="form-control" placeholder="Password"  name ="password" required>
    <label class="checkbox">
        <input type="checkbox" name="remember-me"> Remember me
    </label>
    <div class='form-group' style="margin: 0px;">
        <label for="submit-btn" class="control-label" style="padding-top:4%;" ><a href="/recovery" class="pull-left" tabindex="-1">Recover your account</a></label>
        <div class="pull-right">
            <button class="btn btn-lg btn-primary " type="submit" id="submit-btn">Sign in</button>
        </div>
    </div>
    <div class='clearfix'></div>
</form>