<ol style="color:red;">
<?php foreach ($this->errors as $error) : ?>
    <li><?php echo $error ?></li>
<?php endforeach; ?>
</ol>
<style>
    input{display: block}
</style>
<form action="/auth/signup" method="post">
    <input type="text" name="username" placeholder="Your username" />
    <input type="text" name="email" placeholder="Email address" />
    <input type="password" name="password" placeholder="Password" />
    <input type="password" name="conf-password" placeholder="Confirm Password" />
    <input type="submit" value="Signup" />
</form>