<style>
    div.radio{margin-top: 0}
    .form-group[checked]{background-color: #eee}
    table.table tr td{width: 50%}
</style>
<?php if(isset($this->errors)) \zinux\kernel\utilities\debug::_var($this->errors); ?>
<form action='/profile/avatar?<?php echo \zinux\kernel\security\security::GetHashString(array(\core\db\models\user::GetInstance()->user_id, \session_id())); ?>' method="POST" enctype="multipart/form-data"> 
    <legend>Avatar Manager</legend>
    <table class='table table-responsive'>
        <tbody>
            <tr>
                <td>
                    <div class='form-group'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::FACEBOOK ?>" tabindex="-1"  <?php echo @$this->avatar->activated == core\ui\html\avatar::FACEBOOK ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'>Facebook Account or ID</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control'  name='<?php echo \core\ui\html\avatar::FACEBOOK ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::FACEBOOK}->id ?>" />
                    </div>
                </td>
                <td>
                    <div class='form-group'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::TWITTER ?>" tabindex="-1"  <?php echo @$this->avatar->activated == core\ui\html\avatar::TWITTER ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'>Twitter Account or ID</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::TWITTER ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::TWITTER}->id ?>"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form-group'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::INSTAGRAM ?>" tabindex="-1" <?php echo @$this->avatar->activated == core\ui\html\avatar::INSTAGRAM ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'>Instagram Account or ID</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::INSTAGRAM ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::INSTAGRAM}->id ?>"/>
                    </div>
                </td>
                <td>
                    <div class='form-group'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::GRAVATAR ?>" tabindex="-1" <?php echo !@$this->avatar->activated || @$this->avatar->activated == core\ui\html\avatar::GRAVATAR ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'>Gravatar email</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::GRAVATAR ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::GRAVATAR}->id ?>"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form-group'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="custom" tabindex="-1">
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'>Or custum upload</label>
                        <div class='clearfix'></div>
                        <input type="hidden" name="MAX_FILE_SIZE" value="<?php /* 2MB */ ?>2097152" />
                        <input type='file' class='form-control' style="" name="custom" />
                    </div>
                </td>
                <td>
                    <?php if(@$this->avatar->custom): ?>
                        <?php if(file_exists(".".$this->avatar->custom->thumb_image)) : ?>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="custom" tabindex="-1">
                                Activate
                            </label>
                        </div>
                    <blockquote class='block pull-left'>You currenlty uploaded avatar!</blockquote>
                    <img height="200" width="200" src='<?php echo $this->avatar->custom->thumb_image ?>' class='imageblock img-responsive img-thumbnail pull-right'/>
                        <?php else: ?>
                    <blockquote class='text-danger' style='margin-top:5%'>It seems your privious avatar has been deleted!</blockquote>
                        <?php endif; ?>
                    <?php else: ?>
                    <blockquote class='text-muted' style='margin-top:5%'>No custom avatar has been registered.</blockquote>
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>
    </div>
    <div class="modal-footer">
        <a href="/profile" class="btn btn-default" data-dismiss="modal">Close</a>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>
<?php \zinux\kernel\utilities\debug::_var($this->avatar) ?>