<script src="/access/js/Jcrop/js/jquery.Jcrop.min.js"></script>
<link rel="stylesheet" href="/access/js/Jcrop/css/jquery.Jcrop.min.css" type="text/css" />
<script type="text/javascript">
    <?php 
    list($width, $height) = \getimagesize(".".$this->avatar->image); 
    echo 
    "$(document).ready(function(){
        $('#cropbox').Jcrop({
            onChange: updateCropCoords,
            onSelect: updateCropCoords,
            boxWidth: '100%', 
            boxHeight: '800',
            trueSize: [$width, $height],
            minSize: [200, 200],
            setSelect: [ 
                Math.round($width/2)-Math.round($width/4),
                Math.round($height/2)-Math.round($height/4),
                Math.round($width/2)+Math.round($width/4),
                Math.round($height/2)+Math.round($height/4)
            ],
            aspectRatio: 1/1
        });
    });"
    ?>
    function updateCropCoords(c) { $('#x').val(c.x); $('#y').val(c.y); $('#w').val(c.w); $('#h').val(c.h); }
</script>
<div class="container">
    <legend class="text-muted">Crop avatar</legend>
    <!-- This is the form that our event handler fills -->
    <form action="/profile/avatar/crop" class="form" method="POST" style="margin-bottom: 0;margin-top: -10px">
        <input type="hidden" size="4" id="x" name="x" />
        <input type="hidden" size="4" id="y" name="y" />
        <input type="hidden" size="4" id="w" name="w" />
        <input type="hidden" size="4" id="h" name="h" />
        <div class="form-actions" >
            <div class="">
                <button type="submit" class="btn btn-primary pull-right"  style="margin-left: 10px"><span class='glyphicon glyphicon-compressed'></span> Crop</button>
                <a href="/profile" class="btn btn-default pull-right" ><span class='glyphicon glyphicon-map-marker'></span>  Back to Profile</a>
            </div>
        </div>
    </form>
    <div class="clearfix"></div>
    <center style="border-top: 1px solid #DDD;margin-top: 10px;padding-top: 10px;">
        <!-- This is the image we're attaching Jcrop to -->
        <img src="<?php echo $this->avatar->image ?>" id="cropbox" class="img-responsive" style="border: 1px solid #000;max-height: 800px" height="800" />
    </center>
</div>