<style>
    div.radio{margin-top: 0}
    .form-group[checked]{background-color: #eee}
    table.table tr td{width: 50%}
</style>
<form action='/profile/avatar?<?php echo \zinux\kernel\security\security::GetHashString(array(\core\db\models\user::GetInstance()->user_id, \session_id())); ?>' method="POST" enctype="multipart/form-data"> 
    <legend class="text-muted" style="margin-bottom: 1%">Avatar Manager</legend>
<?php if(isset($this->errors)): ?>
    <legend class="text-danger" >Errors</legend>
    <blockquote class="text-danger" style="margin: 0;">
        <ol>
            <?php foreach ($this->errors as $error): ?>
            <li><?php echo $error ?></li>
            <?php endforeach; ?>
        </ol>
    </blockquote>
<?php endif; ?>
    <table class='table table-responsive'>
        <tbody>
            <tr>
                <td colspan="2" style="border-top: 0;">
                    <div class="form-group pull-right">
                        <a href="/profile" class="btn btn-default" style="width: 80px">Cancel</a>
                        <button type="submit" class="btn btn-primary" style="width: 80px">Save</button>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form-group <?php echo @$this->errors[\core\ui\html\avatar::FACEBOOK]?"has-error":""?>'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::FACEBOOK ?>" tabindex="-1"  <?php echo @$this->avatar->activated == core\ui\html\avatar::FACEBOOK ? "checked" : "" ?> >
                                Activate
                            </label>
                        </div>
                        <br class="gravatar-break"/>
                        <label class='control-label pull-left gravatar'><span class="glyphicon glyphicon-chevron-right"></span> Facebook Account or ID</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control'  name='<?php echo \core\ui\html\avatar::FACEBOOK ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::FACEBOOK}->id ?>" />
                    </div>
                </td>
                <td>
                    <div class='form-group <?php echo @$this->errors[\core\ui\html\avatar::TWITTER]?"has-error":""?>'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::TWITTER ?>" tabindex="-1"  <?php echo @$this->avatar->activated == core\ui\html\avatar::TWITTER ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <br class="gravatar-break">
                        <label class='control-label pull-left gravatar'><span class="glyphicon glyphicon-chevron-right"></span> Twitter Account or ID<?php echo \str_repeat("&nbsp;", 7); ?></label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::TWITTER ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::TWITTER}->id ?>"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form-group <?php echo @$this->errors[\core\ui\html\avatar::INSTAGRAM]?"has-error":""?>'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::INSTAGRAM ?>" tabindex="-1" <?php echo @$this->avatar->activated == core\ui\html\avatar::INSTAGRAM ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <br class="gravatar-break"/>
                        <label class='control-label pull-left gravatar'><span class="glyphicon glyphicon-chevron-right"></span> Instagram Account or ID</label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::INSTAGRAM ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::INSTAGRAM}->id ?>"/>
                    </div>
                </td>
                <td>
                    <div class='form-group <?php echo @$this->errors[\core\ui\html\avatar::GRAVATAR]?"has-error":""?>'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="<?php echo \core\ui\html\avatar::GRAVATAR ?>" tabindex="-1" <?php echo !@$this->avatar->activated || @$this->avatar->activated == core\ui\html\avatar::GRAVATAR ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                        <br class="gravatar-break"/>
                        <label class='control-label pull-left gravatar' id="gravatar-orig"><span class="glyphicon glyphicon-chevron-right"></span> Gravatar email <?php echo \str_repeat("&nbsp;", 17); ?></label>
                        <div class="clearfix"></div>
                        <input type='text' class='form-control' name='<?php echo \core\ui\html\avatar::GRAVATAR ?>' value="<?php echo @$this->avatar->{\core\ui\html\avatar::GRAVATAR}->id ?>"/>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class='form-group <?php echo @$this->errors["custom"]?"has-error":""?>'>
                        <div class="radio pull-right inline">
                            <label>
                                <input type="radio" name="activated"  value="custom" tabindex="-1">
                                Activate
                            </label>
                        </div>
                        <label class='control-label pull-left'><span class="glyphicon glyphicon-chevron-right"></span> Or custum upload</label>
                        <div class='clearfix'></div>
                        <input type="hidden" name="MAX_FILE_SIZE" value="<?php /* 2MB */ ?>2097152" />
                        <input type='file' class='form-control' style="" name="custom" />
                    </div>
                </td>
                <td>
                    <?php if(@$this->avatar->custom): ?>
                        <?php if(file_exists(".".$this->avatar->custom->thumb_image)) : ?>
                        <div class="radio pull-right" >
                            <label>
                                <input type="radio" name="activated"  value="custom" tabindex="-1" <?php echo @$this->avatar->activated == "custom" ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                    <a href="/profile/avatar/delete/1" class="pull-left" style="margin-right: 10px"><span class="glyphicon glyphicon-trash" ></span> Delete the custom avatar</a>
                    <link rel="stylesheet" href="/access/css/mosaic.css" type="text/css" media="screen">
                    <style>
                        .mosaic-block{background: #000 url('/access/img/progress.gif') no-repeat center center;}
                    </style>
                    <div class="clearfix"></div>
                        <style>
                            @media screen and (min-width: 400px) { .mosaic-block{min-width: 200px;display: block;min-height: 200px;}}
                        </style>
                        <div class="mosaic-block bottom-bar pull-right">
                            <a  class="mosaic-overlay" style="display: inline; left: 0px; bottom: -50px;">
                                <div class="details text-center ">
                                    <h1>Current custom avatar<br /><span class="glyphicon glyphicon-picture"></span></h1>
                                </div>
                            </a>
                            <?php $this->profile = \core\db\models\profile::getInstance(\core\db\models\user::GetInstance()->user_id); ?>
                            <?php $def_avatar = "/access/img/anonymous-".($this->profile->is_male?"":"fe")."male.jpg"; ?>
                            <img id="thumbnail" width="200" height="200" class='img-responsive img-thumbnail' src="<?php echo $this->avatar->custom->thumb_image ?>" onerror="this.src='<?php echo $def_avatar ?>';"/>
                        </div>
                        <?php else: ?>
                    <blockquote class='text-danger' style='margin-top:5%'>It seems your privious avatar has been deleted!</blockquote>
                        <?php endif; ?>
                    <?php else: ?>
                        <div class="radio pull-right" >
                            <label>
                                <input type="radio" name="activated"  value="custom" tabindex="-1" <?php echo @$this->avatar->activated == "custom" ? "checked" : "" ?>>
                                Activate
                            </label>
                        </div>
                    <link rel="stylesheet" href="/access/css/mosaic.css" type="text/css" media="screen">
                    <style>
                        .mosaic-block{background: #000 url('/access/img/progress.gif') no-repeat center center;}
                    </style>
                    <div class="clearfix"></div>
                        <style>
                            @media screen and (min-width: 400px) { .mosaic-block{min-width: 200px;display: block;min-height: 200px;}}
                        </style>
                        <div class="mosaic-block bottom-bar pull-right">
                            <a  class="mosaic-overlay" style="display: inline; left: 0px; bottom: -50px;">
                                <div class="details text-center ">
                                    <h1>Default avatar<br /><span class="glyphicon glyphicon-picture"></span></h1>
                                </div>
                            </a>
                            <?php $this->profile = \core\db\models\profile::getInstance(\core\db\models\user::GetInstance()->user_id); ?>
                            <?php $def_avatar = "/access/img/anonymous-".($this->profile->is_male?"":"fe")."male.jpg"; ?>
                            <img id="thumbnail" width="200" height="200" class='img-responsive img-thumbnail' src="<?php echo $def_avatar ?>" />
                        </div>
                    <?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>
</form>