<style type="text/css">
    .transparent {
        /* IE 8 */
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
        /* IE 5-7 */
        filter: alpha(opacity=80);
        /* Netscape */
        -moz-opacity: 0.8;
        /* Safari 1.x */
        -khtml-opacity: 0.8;
        /* Good browsers */
        opacity: 0.8;
    }
    .transparent-clear {
        /* IE 8 */
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)"!important;
        /* IE 5-7 */
        filter: alpha(opacity=100)!important;
        /* Netscape */
        -moz-opacity: 1!important;
        /* Safari 1.x */
        -khtml-opacity: 1!important;
        /* Good browsers */
        opacity: 1!important;
    }
    body{background-color: #404040;}
    #cover-selection {
        position: fixed;
        width: 100%;
        height: 170px;
        background-color: #000;
        padding: 20px;
        bottom: 0px;
        border-top: 3px solid #013a54;
    }
    #cover-selection #placeholder img{
        border: 3px solid #FFF;
        display: inline;
        cursor: pointer;
        margin-right: 10px;
    }
    #cover-selection #placeholder img:last-child {margin-right: 0}
    .container#outline-image img {width: 1200px!important;max-height: 410px!important;}
</style>
<div style="margin: auto -15px;padding-top: 10%;">
    <div style="" class="">
        <div class="container" id="outline-image">
            <div class="row">
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="transparent" id="cover-selection">
        <div class="transparent-clear" id="placeholder" style="overflow-x: scroll;white-space: nowrap;padding-bottom: 10px; padding-top: 10px">
        </div>
    </div>
</div>
<script>
    (function(){ 
        var images = (JSON.parse('<?php echo str_replace("\n", "", addslashes(file_get_contents("./access/img/upload/cover/samples/info.json"))); ?>'));
        var basedir = '/access/img/upload/cover/samples';
        for(var i in images) {
            $("#cover-selection #placeholder").append("<img src='"+basedir + "/" + images[i].file_name+"' class='cover-"+images[i].file_name+"' width='200' height='100' class='image'/>");
        }
        $("#cover-selection #placeholder img").click(function() {
            var $this = $(this).clone();
            $(".container#outline-image .row").html($this.removeAttr('width').removeAttr('height').addClass('img-responsive img-thumbnail'));
        });
        $("#cover-selection #placeholder img:first").click();
    })(jQuery);
</script>