<?php 
    list($avatar_uri , $def_avatar) = \core\ui\html\avatar::get_avatar_link($this->profile->user_id);
   $is_profile_owner = @$this->is_owner;
    $p = $this->profile->to_array();
    $p["full_name"] = $this->user->get_RealName_or_Username();
    unset($p["settings"]); 
    $pj = json_encode($p);
    /**
     * Validates if we should render a section of array as profile info
     */
    $should_render = function(array $p, $section) {
        if(!is_string($section)) throw new \zinux\kernel\exceptions\invalidArgumentException("The arg `section` is not string");
        if(!strlen($section)) throw new \zinux\kernel\exceptions\invalidArgumentException("The arg `section` cannot be empty");
        if(!array_key_exists($section, $p)) throw new \zinux\kernel\exceptions\invalidArgumentException("The arg `$section` does not exists in array `p`");
        switch($section) {
            case "birth_day":
            case "birth_month":
            case "birth_year":
                return $p[$section] != 0;
            case "is_male":
                return $p[$section] != -1;
            default: 
                if(is_string($p[$section]))
                    return strlen($p[$section]);
                if(is_array($p[$section]))
                    return count($p[$section]);
                throw new \zinux\kernel\exceptions\invalidOperationException("The arg `\$p[\$section]` is not neighed `string` nor `array`!!!");
        }
    };
    $inf = array();
    foreach($p as $key => $value) {
        $l = "$key";
        $v = "";
        $s = "basic";
        $convert_labels = array(
                "is_male" => "gender",
                "intro" => "introduction",
                "occu" => "occupation",
                "edu" => "education",
                
        );
        $convert_section = array(
           "phone" => "contact",
           "site" => "contact",
           "public_email" => "contact",
            "intro" => "bio",
            "occu" => "bio",
            "edu" => "bio",
        );
        if(in_array($key, array("user_id", "last_name", "first_name", "full_name", "created_at", "updated_at")))
                continue;
        if(key_exists($key, $convert_labels))
                $l = $convert_labels[$key];
        if(key_exists($key, $convert_section))
                $s = $convert_section[$key];
        switch($key) {
            case "birth_day":
            case "birth_month":
                $l = "Birth Date";
                 if($should_render($p, "birth_month"))
                     $v = date('F ', mktime(0, 0, 0, $p["birth_month"]));
                 if($should_render($p, "birth_day"))
                     $v .= $p["birth_day"];
                 $key = "birth_date";
                 break;
            case "country":
            case "city":
                $l = "Location";
                if($should_render($p, "country"))
                    $v = $p["country"];
                if($should_render($p, "city"))
                    $v .= (($should_render($p, "country") ? ", ": " ") . $p["city"]);
                $key = "location";
                break;
            default:
__DEFAULT_OPS:
                 $l =ucwords(str_replace("_", " ", $l));
                 if($should_render($p, $key))
                         $v = $value;
        }
        if(!strlen($v) && $is_profile_owner)
            $v = '<span class="small text-muted">Not specified</span>';
        if(strlen($v)) {
            $k = "";
            $step = 1;
            // the UI span row#
            $span = 1;
            switch($s) {
                case "basic": $k = "Basic Information"; break;
                case "bio": $k = "Biography "; $step = $span = 2;break;
                case "contact": $k = "Contact Information"; $step = 3; break;
                default: throw new zinux\kernel\exceptions\invalidArgumentException("Undefined `section` value: $s");
            } 
            $inf[$s]["label"] = $k;
            $inf[$s]["span"] = $span;
            $inf[$s]["class"] = $s;
            $inf[$s]["options"] = $is_profile_owner ? "<span class='small pull-right'><a href='/profile/edit/step/$step'>Edit</a></span>" : "";
            $inf[$s]["values"][$key]["label"] = $l;
            $inf[$s]["values"][$key]["value"] = $v;
        }
    }
    $info = array(@$inf["basic"], @$inf["contact"], @$inf["bio"]);
    unset($inf);
?>
<div class='row' style=''>
    <div class="pull-left col-md-3 col-sm-4 col-xs-4 avatar">
        <div class="row" style="margin:10px;width: 100%">
            <div class=" text-center" style="background-color: transparent;width: 100%">
                <div class='mosaic-block bottom-bar icenter-block'>
                <?php if($is_profile_owner) : ?>
                    <a id="change-avatar" href="#"  class="mosaic-overlay" style="display: inline; left: 0px; bottom: -45px;">
                        <div class="details text-center ">
                            <h1><span class="glyphicon glyphicon-picture"></span><br /><b>Change</b></h1>
                        </div>
                    </a>
                    <a class="mosaic-overlay" href="/profile/avatar/crop"style="display: inline; left: 0px; top: -45px;height: 80px;" title="Crop the thumbnail image">
                        <div class="details text-center">
                            <h1>
                                <span class="glyphicon glyphicon-compressed" style="margin-top: 50px;"></span>
                            </h1>
                        </div>
                    </a>
                <?php endif ; ?>
                    <a href="/profile/avatar/view/<?php echo $this->profile->user_id, "?", \zinux\kernel\security\security::GetHashString(array($this->profile->user_id)) ?>" title="Click to view the original avatar">
                        <img id="thumbnail" class='image img-thumbnail img-responsive 'src="<?php echo $avatar_uri ?>" onerror="this.src='<?php echo $def_avatar ?>';"  />
                    </a>
                </div>
                <div class='clearfix'></div>
                <div  class='' style='margin-top: 10px; overflow: hidden;word-break: break-all'>
                    <div class='text'>
                        <strong><?php echo $p["full_name"] ?></strong>
                    </div>
                    <div class='text-muted block small' style='margin-top:10px;'>
                        <span class='glyphicon glyphicon-flag'></span> Joined at <?php echo date("M Y", strtotime($p["created_at"])); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style type='text/css'>
        #about .row .about-block{ min-height: 200px}
        #about .row .about-block table{ margin:10px; width: 100%}
        #about .row .about-block .table tr th, 
        #about .row .about-block .table tr td{ border: 0!important; padding: 0;}
        #about .row .about-block .table tr td{  padding-bottom: 4px }
        #about .row .about-block .table tr td:first-child{ color: #89919C; }
        #about .row .about-block .table tr td.info-value {word-break: break-all;overflow: hidden;text-align: justify}
        #about .row .about-block .table.bio tr th:first-child{width: 100px!important;}
        @media screen and (min-width: 0px) and (max-width: 500px) {
            .clearfix.hidden {display: block!important}
            .avatar {width:100%!important}
            .col-md-6{width: 110%!important}
        }
        @media screen and (min-width: 520px) and (max-width: 990px) {
            .col-md-6{width: 100%!important}
        }
    </style>
<script type='text/javascript'>
    $(document).ready(function() {
        var info = JSON.parse('<?php echo addslashes(json_encode($info)); ?>');
        var prev = null;
        var html = "";
        var item_added = 0;
        var index_processed = -1;
        this.addInfo = function(html) {
            html += "</div>";
            $("#about").append(html);
            prev = null;
            html = "";
            item_added++;
            index_processed = 0;
        };
        this.getValues = function(values, table_class) {
            if(typeof(table_class) === "undefined")
                table_class = "";
            table_class += " table";
            var html = "<table class='"+table_class+"' style='width: 100%'>"+
                        "<thead>"+
                            "<tr>"+
                                "<th class='col-md-4'></th>"+
                                "<th></th>"+
                            "</tr>"+
                        "</thead>"+
                        "<tbody>";
            for(var v in values) {
                html += "<tr class='"+v+"'>"+
                        "<td class='info-label'>"+
                            values[v].label+
                        "</td>"+
                        "<td class='info-value'>"+
                            values[v].value+
                        "</td>";
            }
            html +="</tbody></table>";
            return html;
        };
        this.__render = function(info) {
            for(var block in info) {
                var b = info[block];
                index_processed++;
                if(info.length === 1)
                    b.span = 2;
                if(    
                    index_processed && 
                    index_processed % 2 === 0 || 
                    prev === null || 
                    prev.span * 6 === 12 || 
                    b.span * 6 === 12) {
                        if(html.length) {
                            this.addInfo(html);
                            prev = null;
                            html = "";
                            item_added++;
                            index_processed = 0;
                        }
                        html = "<div class='row'>";
                }
                html += 
                        "<div class='col-md-"+(6 * b.span).toString()+" col-sm-12 col-xs-12 about-block'>"+
                            "<legend><span class='glyphicon glyphicon-map-marker'></span> "+b.label+"</legend>"+
                            "<div class='pull-right' style='margin-top:-42px;'>"+b.options+"</div>"+
                            this.getValues(b.values, b.class)+
                        "</div>";
                if(prev === null)
                    prev = b;
                else if(prev.span * 6  === 6 || prev.span * 6 === 12) {
                    this.addInfo(html);
                    prev = null;
                    html = "";
                    item_added++;
                    index_processed = 0;
                }
            }
            if(html.length)
                this.addInfo(html);
            else if(!item_added) {
                $('.avatar')
                        .removeAttr('class')
                        .addClass('avatar');
            }
        };
        this.__render(info.filter(function(n){ return n !== undefined && n !== null; }));
    });
</script>
    <div class='clearfix hidden'></div>
    <div class="pull-left col-md-9 col-sm-8 col-xm-8">
        <div id="about" class=''>
        </div>
    </div>
</div>
<?php if($is_profile_owner): ?>
<form name="avatar" class="hidden" action="/profile/avatar/?<?php echo \zinux\kernel\security\security::GetHashString(array(\core\db\models\user::GetInstance()->user_id, session_id())) ?>" method="POST" enctype="multipart/form-data">
    <input type="file" name="upload-avatar" accept="image/*"/>
</form>
<script type="text/javascript">
    (function(){
        $("a#change-avatar").click(function(e){
            e.preventDefault();
            $("input[name='upload-avatar']").click();
            if(typeof(window.is_check_cover_load_in_effect) === "undefined")
                window.is_check_cover_load_in_effect = 0;
            $("input[name='upload-avatar']").val('');
            function check_cover_load(){
                window.is_check_cover_load_in_effect = 1;
                if($("input[name='upload-avatar']").val().length) {
                    // time to load the selected image
                    // no need for further change-avatar click event
                    // which can be bug-prone
                    $("a#change-avatar").unbind('click');
                    // NOT any more `check_cover_load` is in effect
                    delete(window.is_check_cover_load_in_effect);
                    // invoke cover-load event
                   $("a#change-avatar").trigger('load-cover');
                    // do not proceed to next interval call
                    return;
                }
                setTimeout(check_cover_load, 750);
            };
            if(!window.is_check_cover_load_in_effect)
                setTimeout(check_cover_load, 500);
        }).on("load-cover", function(){
            window.load_bar();
            $("form[name='avatar']").submit();
        });
    })(jQuery);
</script>
<?php endif; ?>