<?php 
    $p = $this->profile->to_array();
    $p["full_name"] = $this->user->get_RealName_or_Username();
    unset($p["settings"]); 
    $pj = json_encode($p);
    $render_avatar = function(zinux\kernel\view\baseView $view) {
         list($avatar_uri , $def_avatar) = \core\ui\html\avatar::get_avatar_link($view->profile->user_id);
        $is_profile_owner = (@\core\db\models\user::GetInstance()->user_id == $view->profile->user_id); 
?>
        <div class="mosaic-block bottom-bar img-thumbnail" style="background-color: transparent;width: 100%">
        <?php if($is_profile_owner) : ?>
            <a href="/profile/avatar"  class="mosaic-overlay" style="display: inline; left: 0px; bottom: -45px;">
                <div class="details text-center ">
                    <h1><span class="glyphicon glyphicon-picture"></span><br /><b>Change Avatar</b></h1>
                </div>
            </a>
        <?php endif ; ?>
            <a href="/profile/avatar/view/<?php echo $view->profile->user_id, "?", \zinux\kernel\security\security::GetHashString(array($view->profile->user_id)) ?>" target="__blank">
                <img id="thumbnail" width="200" height="200" class='col-lg-12 img-responsive img-thumbnail' src="<?php echo $avatar_uri ?>" onerror="this.src='<?php echo $def_avatar ?>';"  />
            </a>
        </div>
<?php
    }
?>
<script type="text/javascript">
    $(document).ready(function() {
        var p = JSON.parse('<?php echo $pj ?>');
        console.log(p);
    });
</script>
<div class='row' style=''>
    <div class="pull-left col-md-3">
        <?php $render_avatar($this); ?>
        <div class='clearfix'></div>
        <div class="row text-center" style="margin:10px;width: 100%">
            <div>
                <strong><?php echo $p["full_name"], "<br />", strlen($p["nick_name"]) ? "( {$p["nick_name"]} )" : "( nick Name  saknsa ska )"  ?></strong>
            </div>
            <div style='margin-top: 10px;'>
                <span class='glyphicon glyphicon-flag'></span> Joined at <?php echo date("M Y", strtotime($p["created_at"])); ?>
            </div>
        </div>
    </div>
    <style type='text/css'>
        #about .row .about-block{ min-height: 200px}
        #about .row .about-block table{ margin:10px; width: 100%}
        #about .row .about-block .table tr th, 
        #about .row .about-block .table tr td{ border: 0!important; padding: 0; }
        #about .row .about-block .table tr td{ padding-top: 4px; }
        #about .row .about-block .table tr td:first-child{ color: #89919C; }
        @media screen and(min-width: 550px) {
            .clearfix.hidden-sm {display: none!important}
            #about {display: none}
        }
    </style>
    <div class='clearfix hidden-lg hidden-md hidden-sm'></div>
    <div class="pull-left col-md-9 col-sm-8 col-xm-12">
        <div id="about" class=''>
            <div class='row' style=''>
                <div class='col-md-6 about-block' style=''>
                    <legend>Basic Information</legend>
                    <table class='table' style='width: 100%'>
                        <thead>
                            <tr>
                                <th class='col-md-4'></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Gender</td>
                                <td>Male</td>
                            </tr>
                            <tr>
                                <td>Gender</td>
                                <td>Male</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class='col-md-6 about-block' style=''>
                    <legend>Basic Information</legend>
                </div>
            </div>
            <div class='row'>
                <div class='col-md-6 about-block' style=''>
                    <legend>Basic Information</legend>
                </div>
                <div class='col-md-6 about-block' style=''>
                    <legend>Basic Information</legend>
                </div>
            </div>
        </div>
    </div>
</div>
<?php unset($render_avatar); ?>