<?php if(!isset($this->posts)) throw new zinux\kernel\exceptions\invalidArgumentException("No `\$posts` arg. supplied"); ?>
<?php $is_profile_owner = @$this->is_owner;  ?>
<?php $is_preview_mode = @$this->preview_mode; ?>
<div class="container col-lg-8  col-md-8  col-sm-8 col-xm-12 posts">
<?php if(count($this->posts)): ?>
    <?php if(!isset($this->request->params["infscroll"])): ?>
    <link type="text/css" rel="stylesheet" href="/access/css/posts.css" />
    <?php endif; ?>
    <?php foreach($this->posts as $post): ?>
        <?php modules\opsModule\models\post::__render_summary($post); ?>
    <?php endforeach; ?>
<?php else: ?>
    <div class="row article">
        <style>
            .error-header { border: 1px solid #cccccc; padding: 10px; font-weight: bold}
        </style>
        <article style="margin-bottom: 10px;margin-top: 10px;">
            <div class="error-404 text-center">
                <div class="error-header">
                    <span class="glyphicon glyphicon-warning-sign"></span> There are no more public article. 
                </div>
            </div>
        </article>
    </div>
<?php endif; ?>
    <div class='form-actions next-prev-link article' style='border-top:1px solid #DDD;padding-top:40px;padding-bottom: 40px;'>
<?php if($this->request->params["page"] > 1): ?>
        <a class='btn btn-link pull-left prev-page' rel="previous" href="/profile/<?php echo $is_preview_mode ? "preview/" : "" ?>posts/<?php echo $is_profile_owner ? "" : $this->profile->user_id."/0/" /* The `0` is for don't get params like {USER_ID => PAGE} in server side */?>page/<?php echo count($this->posts) ? $this->request->params["page"] - 1:  ceil($this->total_count / $this->fetch_limit) ?>"><span class='glyphicon glyphicon-arrow-left'></span> Previous Page</a>
<?php endif; ?>
<?php if($this->is_more_note): ?>
        <a class='btn btn-link pull-right next-page' rel="next" href="/profile/<?php echo $is_preview_mode ? "preview/" : "" ?>posts/<?php echo $is_profile_owner ? "" : $this->profile->user_id."/0/" /* The `0` is for don't get params like {USER_ID => PAGE} in server side */?>page/<?php echo $this->request->params["page"] + 1 ?>">Next Page <span class='glyphicon glyphicon-arrow-right'></span></a>
<?php endif; ?>
        <div class='clearfix'></div>
    </div>
</div>
<?php if(isset($this->timeline) && count($this->timeline)) : ?>
<div class="pull-right row hidden-sm hidden-xs  hidden-print" >
    <style type="text/css">ul.timeline li {border-right: 7px #88ccff solid;margin-bottom: 7px;height: 30px;padding:3px;padding-left: 10px;}ul.timeline li.active {border-right: 7px #004488 solid;}ul.timeline li.active a{color:#004488;font-weight: bolder;}</style>
    <div class="sticky">
        <div style="z-index: 1000;margin-top:10px;margin-left: -70px;">
            <ul class="list-unstyled timeline">
    <?php
                $tl_found = false;
                $ctl = $this->request->params["timeline"];
                if(($tl_found = $ctl > $this->timeline[0])) :
    ?>
                <li class="active year-<?php echo $ctl; ?>">
                    <a href="/@<?php echo $this->user->username ?><?php echo $is_preview_mode ? "/preview/" : "" ?>/posts/~/timeline/<?php echo $ctl ?>"><?php echo $ctl; ?></a>
                </li>
                <li class="text-center" style="padding-right: 20px;">
                    <a style="cursor: pointer">...</a>
                </li>
                <?php endif; foreach($this->timeline as $time) : $tl_found |= ($ctl == $time); ?>
                <li class='<?php echo $ctl == $time ? "active": "" ?> year-<?php echo $time; ?>'>
                    <a href="/@<?php echo $this->user->username ?><?php echo $is_preview_mode ? "/preview/" : "" ?>/posts/~/timeline/<?php echo $time ?>"><?php echo $time; ?></a>
                </li>
                <?php endforeach; ?>
                <?php if(!$tl_found) : ?>
                <li class="text-center" style="padding-right: 20px;">
                    <a style="cursor: pointer">...</a>
                </li>
                <li class="active year-<?php echo $ctl; ?>">
                    <a href="/@<?php echo $this->user->username ?><?php echo $is_preview_mode ? "/preview/" : "" ?>/posts/~/timeline/<?php echo $ctl ?>"><?php echo $ctl; ?></a>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if(!isset($this->request->params["infscroll"])): ?>
    <link rel="stylesheet" href='/access/google-code-prettify/tomorrow-night.theme.min.css' />
    <script type="text/javascript" src="/access/google-code-prettify/prettify.js"></script>
    <script type="text/javascript" src="/access/js/sticky/jquery.sticky.min.js"></script>
    <script type='text/javascript'>
        (function(){
            prettyPrint();
            $(".sticky").sticky();
        })();
    </script>
    <?php if($this->is_more_note): ?>
        <script type="text/javascript" src="/access/js/jscroll/jquery.jscroll.min.js"></script>
        <script type="text/javascript">
            (function(){
                var jscroll_callback = function() {
                    $('.next-prev-link')
                            .hide()
                            .children(".next-page")
                                .each(function(index, elem) {
                                    $(elem).attr('href', $(elem).attr('href') + "?infscroll=1");
                                });
                    if($('.error-404').length !== 0)
                        // destroy jscroll, the procedure fecthed from internal `_destroy()` function in `jquery.jscroll.js` file
                        $('.posts')
                            .unbind('.jscroll')
                            .removeData('jscroll')
                            .find('.jscroll-inner').children().unwrap()
                            .filter('.jscroll-added').children().unwrap();
                };
                jscroll_callback();
                $('.posts').jscroll({
                    loadingHtml: '<center><img src="/access/img/ajax-loader.gif" alt="Loading" /></center>',
                    nextSelector: 'a.next-page:last',
                    contentSelector: '.article',
                    callback: jscroll_callback
                });
                $(window).scroll(function() {
                    var h = [];
                    $(".row.article").each(function() {
                        var isScrolledIntoView = function (elem){
                            var docViewTop = $(window).scrollTop();
                            var docViewBottom = docViewTop + $(window).height();

                            var elemTop = $(elem).offset().top;
                            var elemBottom = elemTop + $(elem).height();

                            return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
                        };
                        if(isScrolledIntoView(this)) {
                            h.push($(this).find('.year').text());
                        }
                    });
                    if(h.length) {
                        h.sort();
                        h = h[Math.floor((h.length - 1) / 2)];
                        $(".timeline li.year-"+h)
                            .addClass("active")
                            .siblings()
                                .removeClass("active");
                    }
                });
            })(jQuery);
        </script>        
    <?php endif; ?>
<?php endif; ?>