<script src="/access/js/moment.min.js"></script>
<script src="/access/js/jquery.tablesorter.min.js"></script>
<script src="/access/js/jquery.filtertable.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
    <?php if($is_owner): ?>
        window.update_menu_checkbox = function() {
            var all_checked = ($("input[type='checkbox'].item-checkbox:checked").length === $("input[type='checkbox'].item-checkbox").length);
            if($("input[type='checkbox'].item-checkbox:checked").length === 0) {
                $("input[type='checkbox'].check-all").prop("indeterminate", false);
                $("input[type='checkbox'].check-all").prop("checked", false);
                $(".checked-opt").addClass("hidden");
                $(".unchecked-opt").removeClass("hidden");
            } else {
                $("input[type='checkbox'].check-all").prop("indeterminate", !all_checked);
                $("input[type='checkbox'].check-all").prop("checked", all_checked);
                $(".checked-opt").removeClass("hidden");
                $(".unchecked-opt").addClass("hidden");
                if($("input[type='checkbox'].item-checkbox:checked").length === 1)
                    $(".checked-opt.checked-opt-unique").removeClass("hidden");
                else
                    $(".checked-opt.checked-opt-unique").addClass("hidden");
            }
        };
        /**
         * Init page table and ajax placeholder
         * @param boolean init if it is a page init?
         */
        window.reset_ajax_placeholder = function(init) {
            if(typeof(init) === "undefined") init = false;
            if(init) {
                $("#ajax-placeholder").html("").hide().css("margin", "0px");
                $("#explorer-table").css({"margin-top": $("#explorer-template").css("height")});
                return;
            }
            $("#ajax-placeholder").slideUp("medium", function() { 
                $(this).html("").hide().css("margin", "0px");
                $("#explorer-table").animate({"margin-top": $("#explorer-template").css("height")}, "fast");
            });
        };
        window.plot_if_no_item_found = function() {
            if($("tr.item-row").length === 0) {
                $("#explorer-table-empty").remove();
                $("#explorer-table").after($('<?php 
                        ob_start();
                        require 'table-empty.phtml';
                    $content = ob_get_clean();
                    echo str_replace("\n", "", $content);
                ?>')).fadeIn();
            }
        };
        window.init_checkboxes = function() {
            // remove if any previously defined `change` event handler
            $("input[type='checkbox'].item-checkbox").unbind('change');
            $("input[type='checkbox'].item-checkbox").change(function() {
                if($(this).prop('checked')) {
                    $(this).parent().parent().css({"background-color": "#f7fafc"});
                    $(this).parent().siblings('.item-name').addClass("item-checked-name");
                    $(this).parent().parent().addClass("item-checked");
                } else {
                    $(this).parent().parent().css("background-color", "transparent");
                    $(this).parent().siblings('.item-name').removeClass("item-checked-name");
                    $(this).parent().parent().removeClass("item-checked");
                }
                window.update_menu_checkbox();
            });
            window.update_menu_checkbox();
        };
        window.init_times = function(updating) {
            if(typeof(updating) === "undefined") updating = false;
            var selection_rule = 'td.updated-at.timeago';
            if(!updating) selection_rule += ':not(.time-inited)';
            $(selection_rule).each(function(){
                var time = moment($(this).find("time").attr("datetime"), 'ddd, DD MMM YYYY HH:mm:ss ZZ').format("lll");
                var time_str = (moment($(this).find("time").attr("datetime"), 'ddd, DD MMM YYYY HH:mm:ss ZZ').fromNow("lll")) + " ago";
                $(this)
                    .attr('title', time)
                    .children('time')
                    .attr('title', $(this).attr('title'))
                    .addClass(".time-inited")
                    .html(time_str);
            });
        };
        window.update_times = function() { window.init_times(true); };
        window.sort_table = function() {
            var defaultHeadIndex = 2;
            var defaultHeadOrder = 0;
            var $activeHead = 'table thead tr th.headerSortDown, table thead tr th.headerSortUp';
            if($($activeHead).length !== 0) {
                defaultHeadIndex = $($activeHead).index();
                defaultHeadOrder = $($activeHead).hasClass('headerSortDown') ? 0 : 1;
            }
            // remove any previous click handler 
            // bound to table's headers if we don't
            // this the next `tablesorter()` will invoke
            // both of handler(i.e the previous handlers 
            // and the following new one) and thing will
            // get messy!!
            $('table.table .header').unbind('click');
            // make/re-make the table sortable
            $('table.table').tablesorter({
                sortList: [[defaultHeadIndex, defaultHeadOrder]],
                textExtraction: function(node) {
                    var txt = $(node).text();
                    if($(node).hasClass('updated-at')) {
                        txt = new Date($(node).attr('origin-date')).getTime();
                    }
                    if($(node).hasClass('status')) {
                        txt = $(node).attr('status') + $(node).next("td").text().trim();
                    }
                    return txt;
                },
                headers:{
                    0: { sorter: false }
                }
            });
        };
        // to make `$("input[type='checkbox'].item-checkbox").change()` auto-invokable!!
        $.propHooks.checked = {
            set: function(elem, value, name) {
              var ret = (elem[ name ] = value);
              $(elem).trigger("change");
              return ret;
            }
        };
        $(".check-all").click(function() {
            $("input[type='checkbox'].item-checkbox").prop("checked", !$("input[type='checkbox'].item-checkbox").prop("checked"));
            window.update_menu_checkbox();
        });
        $(".check-none").click(function() {
            $("input[type='checkbox'].item-checkbox").prop("checked", false);
            window.update_menu_checkbox();
        });
        $(".check-public").click(function() {
            $("input[type='checkbox'].public-item").prop("checked", true);
            $("input[type='checkbox'].private-item").prop("checked", false);
            window.update_menu_checkbox();
        });
        $(".check-private").click(function() {
            $("input[type='checkbox'].public-item").prop("checked", false);
            $("input[type='checkbox'].private-item").prop("checked", true);
            window.update_menu_checkbox();
        });
        $("a.new-item").click(function(e){
            switch($(this).attr("data-tag")) {
                case "folder":
                case "link":
                    e.preventDefault();
                    window.reset_ajax_placeholder();
                    // we need this delay to changes in `window.reset_ajax_placeholder()` have time to get applied
                    setTimeout(function($this) {
                        $.ajax({
                            url: $($this).attr('href').split("#!")[1]+"&suppress_layout=1&continue=<?php echo $this->request->GetURI(); ?>"
                        });
                    }, 400, this);
                    break;
                default:
            }
        });
        window.reset_ajax_placeholder(true);
        window.update_menu_checkbox();
    <?php endif; ?>
        window.ajax_start = function() {
            $("#ajax-placeholder *").prop("readonly", true);
            $(".ajax-loader-img-general").removeClass("hidden");
        };
        window.ajax_stop = function() {
            $(".ajax-loader-img-general").addClass("hidden");
        };
        window.ajax_error = function(){
            $("#ajax-placeholder *").prop("readonly", false).first().focus();
        };
        window.ajax_success = function( event, xhr, settings ) {
            if(typeof(xhr.responseText) === "undefined" || xhr.responseText.length === 0) window.reset_ajax_placeholder();
            else {
                $("#ajax-placeholder")
                    .hide()
                    .html(xhr.responseText + "<small><a href='#' onclick='window.reset_ajax_placeholder();return false;'>Close</a></small>")
                    .css("margin", "-0px auto  10px auto")
                    .slideDown('medium', function() {
                        $("#explorer-table").animate({"margin-top": $("#explorer-template").css("height")}, "fast");
                    });
                setTimeout(function() { $("#ajax-placeholder input").first().focus(); }, 500);
            }
        };
        window.APPLY_NAME_EDITTED = "name-editted";
        window.APPLY_REMOVE = "remove";
        window.apply_change = function(apply_type, data, shouldUpdateTime) {
            if(typeof(data) === "undefined") data = "";
            if(typeof(apply_type) === "undefined") apply_type = "nop";
            if(typeof(shouldUpdateTime) === "undefined") shouldUpdateTime = false;
            switch(String(apply_type).toLowerCase()) {
                case window.APPLY_NAME_EDITTED:
                    // if item has been created?
                    if($("tr.item-checked td.item-checked-name a").length === 0)
                        console.warn("NEW ITEM `APPLY_CHANGE()` NOT IMPLEMENTED");
                    // or it was editted?
                    else
                        $("tr.item-checked td.item-checked-name a").html(data);
                    shouldUpdateTime = true;
                    break;
                case window.APPLY_REMOVE:
                    var to_remove = $("tr.item-checked").length;
                    var all_rows = $("tr.item-row").length;
                    $("tr.item-checked").fadeOut(200, function() { 
                        $(this).remove();
                        window.plot_if_no_item_found();
                        window.update_menu_checkbox();
                        window.reset_ajax_placeholder();
                    });
                    $(".check-none").click();
                    setTimeout(function() {
                        window.$o = (all_rows - to_remove);
                        if(window.$o < 0) window.$o = 0;
                        window.$l = to_remove;
                        if($("#next-prev-container #next-prev-status #total-count").length !== 0) {
                            $("#next-prev-container #next-prev-status #total-count").html(Math.max($("#next-prev-container #next-prev-status #total-count").html() - to_remove, 0));
                            if($("#next-prev-container #next-prev-status #total-count").html() === "0") $("#next-prev-container").remove();
                            else {
                                $("#next-prev-container #next-prev-status #bounds #upper-bound")
                                    .html(Math.min($("#next-prev-container #next-prev-status #total-count").html(), $("#next-prev-container #next-prev-status #bounds #upper-bound").html()));
                                if($("#next-prev-container #next-prev-status #total-count").html() <= '<?php echo FETCH_LIMIT; ?>')
                                   $("#next-prev-container .pagination #right-btn").addClass('disabled').children('a').attr("href", "#");
                            }
                        }
                        window.fetch_more(window.$o - 1);
                        window.$l = <?php echo FETCH_LIMIT; ?>;
                    }, 100);
                    return;
                case "nop": break;
                default:
                    throw "Undefined `"+apply_type+"`!";
            }
            if(shouldUpdateTime) {
                // update the update row
                var updateTime = moment().format('ddd, DD MMM YYYY HH:mm:ss ZZ');
                $("tr.item-checked td.updated-at")
                    .attr('title', updateTime)
                    .attr('origin-date', updateTime)
                    .children('time')
                        .attr('datetime', updateTime)
                        .attr('title', updateTime);
            }
            // tag checked items to be trackable
            $("tr.item-checked").addClass("item-anim-tag");
            // clear any UI applied by checking items
            $(".check-none").click();
            // animate the tagged items
            $('tr.item-anim-tag').hide().fadeIn(2000, function(){
                // remove the tracking tag of tagged items
                $(this).removeClass("item-anim-tag");
            });
            // resort table
            window.sort_table();
        };
        $(window).ajaxStart(window.ajax_start);
        $(window).ajaxStop(window.ajax_stop);
        $(window).ajaxError(window.ajax_error);
        $(window).ajaxSuccess(window.ajax_success);
<?php 
        $mp = new \core\utiles\messagePipe();
        $check = $mp->hasFlow();
        $msgs = "";
        if($check) $msgs = "<ol class='text-info' style='list-style-image: url(\"/access/img/bullet.png\");padding:0;margin-left:15px;'>";
        while(($msg = $mp->read())) $msgs .= "<li>$msg</li>";
        if($check) $msg = "</ol>";
        if($check) :
?>
        setTimeout(function() {
            window.top.open_infoModal('<?php echo addslashes($msgs) ?>', 2700);
        }, 150);
<?php endif; ?>
<?php if(false) : ?>
        $("#explorer-table .table").filterTable({
            minRows: 0,
            highlightClass: "filtered-item",
            filterSelector: '#qacess',
            callback: function(term, table) {
                if($("#explorer-table .table tr.filtered-item").length === 0) {
                    var rows = $("#explorer-table .table .strong-highlighted");
                    rows.each(function(index, elem) {
                        $(elem).children("strong.strong-highlighted-filter").each(function(index, $this) {
                            $($this).replaceWith($($this).text());
                        });
                    });
                    rows.removeClass("strong-highlighted");
                }
                $("#explorer-table .table .filtered-item").each(function(index, elem) {
                    if($(elem).children("a").length) {
                        $(elem)
                            .children("a")
                                .addClass("strong-highlighted")
                                .html($(elem).text().trim().replace(new RegExp(term, "gi"), '<strong class="strong-highlighted-filter">$&</strong>'));
                    }
                });
            }
        });
<?php endif; ?>
    });
</script>