<div class="visible-xs clearfix"></div>
<div style="padding: 0% 0 1% 0;" id="directory-tree-headtypes">
    <?php echo $this->plot_next_prev_links($active_type, $pid, $total_count); ?>
    <ul class="nav nav-tabs" style="font-weight: 900;font-variant: small-caps"><?php
    foreach(array(
            "folders" => "<span class='glyphicon glyphicon-folder-".(strtoupper("{$active_type}") == "FOLDERS"?"open":"close")."'></span>", 
            "notes" => "<span class='glyphicon glyphicon-file'></span>", 
            "links" => "<span class='glyphicon glyphicon-link'></span>") as $key => $value)
    {
        $singleton = array(
           self::TRASH => "/trashes.$key",     
           self::ARCHIVE => "/archives.$key",     
           self::SHARED => "/shared.$key",     
           self::RECENT => "/recent.$key",
           "__default" => "/d/$pid.$key",
        );
        $url = $singleton["__default"];
        if(key_exists($this->tree_type, $singleton))
                $url = $singleton[$this->tree_type];
        echo "<li ".(strtoupper("{$active_type}") == strtoupper($key)?"class='active'":"")." title='".(ucwords($key))."'><a class='table-nav-link' href='$url'>$value</a></li>";
    }
    ?></ul>
</div>