<style>
    #directory-tree-opt {margin: -10px auto 10px auto;}
    #directory-tree-opt .btn{ zoom: 1; filter: alpha(opacity=80); opacity: 0.8; }
    #directory-tree-opt div.btn-group{ margin-right: 10px; }
    #directory-tree-opt .w60{ width: 60px; }
    .explorer-wide {margin: auto -2% auto -2%;padding: 0;}
</style>
<link rel="stylesheet" href="/access/css/generic.css">
<div id="directory-tree-opt" class="btn-toolbar">
<!--    <div class="pull-right" style="width: 25%;">
        <span class="glyphicon glyphicon-remove pull-right" style="cursor: pointer;margin-top: 10px;margin-left: -80px;padding-right: 10px" title="Clear Filter" onclick="$('#qacess').val('').trigger('keyup');"></span>
        <input type="search" style="padding-right: 30px;width: 100%" class="input form-control pull-right" placeholder="Filter by name" id="qacess"/>
    </div>-->
    <!-- Split button -->
    <div class="solid-dropdown  btn-group">
        <div type="button" class="btn btn-default" style="height: 34px;"><input type="checkbox" class="input check-tool  check-all" check-type='all'/></div>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="height: 34px">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
      <ul class="dropdown-menu" role="menu">
          <li><a href="#" class="check-tool check-all" onclick="return false;" check-type='all'>All</a></li>
        <li><a href="#" class="check-tool  check-none" onclick="return false;" check-type='none'>None</a></li>
        <li class="divider"></li>
        <li><a href="#" class="check-tool check-public" onclick="return false;" check-type='public'>Public</a></li>
        <li><a href="#" class="check-tool check-private" onclick="return false;" check-type='private'>Private</a></li>
      </ul>
    </div>
    <div class="btn-group" style="margin-right: 0">
        <a href="<?php echo $this->request->GetURI(); ?>" class="btn btn-default w60"><span class="glyphicon glyphicon-refresh"></span></a>
        <?php if($this->tree_type != self::TRASH && $this->tree_type != self::RECENT) : ?>
        <div class="solid-dropdown btn-group">
            <button type="button" class="btn btn-default dropdown-toggle w60" data-toggle="dropdown" title="Create New Item">
                <strong><span class="glyphicon glyphicon-plus"></span></strong> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right" role="menu">
              <li title="Create A Folder"><a href="#!/new/folder/?pid=<?php echo $pid, \zinux\kernel\security\security::__get_uri_hash_string(array("folder", $pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>" data-tag="folder" class="new-item"><span class="inline glyphicon glyphicon-folder-close"></span> Folder</a></li>
              <li title="Create A Note"><a href="#!/new/note/?pid=<?php echo $pid, \zinux\kernel\security\security::__get_uri_hash_string(array("note", $pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>" data-tag="note" class="new-item"><span class="inline glyphicon glyphicon-file"></span> Note</a></li>
              <li title="Create A Link"><a href="#!/new/link/?pid=<?php echo $pid, \zinux\kernel\security\security::__get_uri_hash_string(array("link", $pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>" data-tag="link" class="new-item"><span class="inline glyphicon glyphicon-link"></span> Link</a></li>
            </ul>
          </div>
        <?php endif; ?>
    </div>
<?php switch($this->tree_type):
    case self::RECENT:
    case self::REGULAR:
    case self::ARCHIVE:
    case self::SHARED:
?>
    <div class="solid-dropdown checked-opt btn-group hidden <?php echo $this->tree_type === self::RECENT ?  "checked-opt-unique"  : "" ?>">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="-webkit-border-radius: 0;-moz-border-radius: 0;border-radius: 0;">
            <strong>Actions <span class="caret"></span></strong>
        </button>
        <ul class="dropdown-menu" role="menu" style="-webkit-border-radius: 0;-moz-border-radius: 0;border-radius: 0;">
            <li><a type="submit" href="#" title="Edit" class="checked-opt checked-opt-unique" name="op" value="edit"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
            <?php if($this->tree_type === self::RECENT)  goto __EOG; ?>
            <li><a type="submit" href="#" title="Move To" name="op" value="move"><span class="glyphicon glyphicon-folder-close"></span> Move To</a></li>
            <li class="divider"></li>
            <li><a type="submit" href="#" title="Toggle Share" name="op" value="share"><span class="glyphicon glyphicon-<?php echo $this->tree_type === self::SHARED? "off":"share-alt" ?>"></span> <?php echo $this->tree_type === self::SHARED? "Un-" : "Toggle " ?>Share</a></li>
<?php if($this->tree_type !== self::SHARED): ?>
            <?php if(($this->tree_type === self::ARCHIVE)&& $this->request->params["d"] == 0): ?>
            <li><a type="submit" href="#" title="Un-Archive" name="op" value="archive"><span class="glyphicon glyphicon-open"></span> Un-archive</a></li>
            <?php elseif($this->tree_type == self::REGULAR) : ?>
            <li><a type="submit" href="#" title="Archive" name="op" value="archive"><span class="glyphicon glyphicon-save"></span> Archive</a></li>
            <?php endif; ?>
<?php endif; ?>
            <li class="divider"></li>
            <li><a type="submit" href="#" title="Delete" name="op" value="trash"><span class="glyphicon glyphicon-trash"></span> Delete</a></li>
<?php __EOG: ?>
        </ul>
    </div>
<?php break;
    case self::TRASH: ?>
    <div class="btn-group checked-opt hidden">
        <button type="submit" class="btn btn-primary" title="Restore" name="op" value="restore"><strong><span class="glyphicon glyphicon-repeat"></span> Restore</strong></button>
    </div>
    <div class="btn-group checked-opt hidden">
        <button type="submit" class="btn btn-warning" title="Remove Permanently" name="op" value="remove"><strong><span class="glyphicon glyphicon-remove"></span> Delete Forever</strong></button>
    </div>
    <div class="small pull-right empty-trash" style="padding-top: 7px;">
        <a href='/trashes/do/empty'>Empty Trash</a>
        <script type="text/javascript">
            $(document).ready(function() {
                if($('.item-row').length === 0)
                    $('.empty-trash').remove();
            });
        </script>
    </div>
<?php break;
    default: throw new \zinux\kernel\exceptions\invalidOperationException("Undefined tree type# `{$this->tree_type}`!"); ?>
<?php endswitch; ?>
    <div class="pull-right">
        <div class="btn-group hidden ajax-loader-img-general" style="margin:0;margin-right: 10px;padding-top: 5px;">
            <img class="image" src="/access/img/ajax-loader.gif" />
        </div>
    </div>
</div> <!--end  menu-->
<div class="clearfix"></div>
<div id="ajax-placeholder" style="margin: 0;">
</div>
<div class="clearfix"></div>