<div class="pull-right" id="next-prev-container">
    <style>
        #next-prev-container .next-prev-link {
            border: 1px solid #DDDDDD;
            border-radius: 0;
        }
        #next-prev-container #next-prev-status {
        }
    </style>
    <div id="next-prev-status" class="btn disabled">
        <strong>1-30</strong> of <strong>2,745</strong>
    </div>
    <a href="#" class="btn next-prev-link" id="next-prev-left"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a href="#" class="btn next-prev-link" id="next-prev-right"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>