<script src="/access/js/jquery.tablesorter.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        window.setInterval(window.update_times, 500);
        window.sort_table = function() {
            var defaultHeadIndex = 2;
            var defaultHeadOrder = 0;
            var $activeHead = 'table thead tr th.headerSortDown, table thead tr th.headerSortUp';
            if($($activeHead).length !== 0) {
                defaultHeadIndex = $($activeHead).index();
                defaultHeadOrder = $($activeHead).hasClass('headerSortDown') ? 0 : 1;
            }
            // remove any previous click handler 
            // bound to table's headers if we don't
            // this the next `tablesorter()` will invoke
            // both of handler(i.e the previous handlers 
            // and the following new one) and thing will
            // get messy!!
            $('table.table .header').unbind('click');
            // make/re-make the table sortable
            $('table.table').tablesorter({
                sortList: [[defaultHeadIndex, defaultHeadOrder]],
                textExtraction: function(node) {
                    var txt = $(node).text();
                    if($(node).hasClass('updated-at')) {
                        txt = new Date($(node).attr('origin-date')).getTime();
                    }
                    if($(node).hasClass('status')) {
                        txt = $(node).attr('status') + $(node).next("td").text().trim();
                    }
                    return txt;
                },
                headers:{
                    0: { sorter: false }
                }
            });
        };
        $("button[name='op']").click(function(e){
            if($(this).attr('value') === 'edit') return;
            e.preventDefault();
            var ops = String($(this).attr('value')).toLowerCase();
            var $this = this;
            switch(ops) {
                case "share":
                    ops = "toggle-share";
                case "remove":
                    var msg = "<u>#"+($("tr.item-checked").length)+"</u> <?php echo $active_type ?>s";
                    if($("tr.item-checked").length === 1) {
                        msg = "<u style='cursor:pointer'>"+$(".item-checked-name a").html()+"</u>";
                    }
                    window.top
                            .open_yesnoModal(
                            "Are your sure to <b>"+ops+"</b> "+msg+"?", 
                            function() {
                                window.submit_ops($this);
                            }
                        );
                    break;
                default:
                    window.submit_ops($this);
            }
        });
        $("button[value='edit']").click(function(e) {
            e.preventDefault();
            if($("input[type='checkbox'].item-checkbox:checked").first() === 0) return;
            <?php if($active_type == "note"): ?>
            window.top.open("/ops/editAPI?<?php echo $active_type ?>="+$("input[type='checkbox'].item-checkbox:checked").first().val()+"<?php echo zinux\kernel\security\security::GetHashString(array($active_type, session_id(), \core\db\models\user::GetInstance()->user_id))?>&continue=<?php echo $this->request->GetURI(); ?>");
            <?php else: ?>
                $.ajax({
                    type: "GET",
                    url: "/ops/editAPI?<?php echo $active_type ?>="+$("input[type='checkbox'].item-checkbox:checked").first().val()+"&suppress_layout=1<?php echo zinux\kernel\security\security::GetHashString(array($active_type, session_id(), \core\db\models\user::GetInstance()->user_id))?>&continue=<?php echo $this->request->GetURI(); ?>"
                });
            <?php endif; ?>
        });
        window.submit_ops = function($this) {
            $('form#opt-form').prepend($("<input>").attr("type", "hidden").attr("name", $($this).attr('name')).val($($this).attr('value')));
            var ops = $($this).attr('value');
            $.ajax({
                type: $('form#opt-form').attr('method'),
                url: $('form#opt-form').attr('action'),
                data: $('form#opt-form').serialize()+"&ajax=1",
                success: function(data) {
                    // unbind the success method to ignore the general result output
                    $(window).unbind('ajaxSuccess');
                    window.top.open_infoModal(data, 2700);
                    switch(String(ops).toLowerCase()) {
                        case "share":
                            window.location = '<?php echo $this->request->getURI(); ?>';
                            return;
                        case "remove":
                        case "restore":
                        case "trash":
                        case "archive":
                            window.apply_change(window.APPLY_REMOVE);
                            break;
                        default:
                            throw "Undefined operation `"+ops+"`!";
                    }
                    // set a timeout(50ms) for re-binding the ajax success method
                    setTimeout(function() { $(window).ajaxSuccess(window.ajax_success); }, 50);
                },
                error: function( jqXHR, textStatus, errorThrown) {
                    window.top.open_errorModal(jqXHR.responseText);
                }
            }).always(function(){
                // remove the simulated form submit btn
                $('form#opt-form input[name="op"]').remove();
            });
        };
        window.$l = <?php echo FETCH_LIMIT; ?>;
        window.$o = <?php echo FETCH_LIMIT; ?>;
        window.fetch_more = function() {
            window.fetching_more = true;
            $(".ajax-loader-img-inf-scroll").removeClass("hidden");
            var sort_base = "";
            var $activeHead = 'table thead tr th.headerSortDown, table thead tr th.headerSortUp';
            var order = $($activeHead).hasClass('headerSortDown') ? 0 : 1;
            switch($($activeHead).index()) {
                default:
                case 2:
                    sort_base = 1;
                    break;
                case 3:
                    sort_base = 2;
                    break;
            };
            $.ajax({
                type: "GET",
                global: false,
                url: "<?php echo $this->request->getURI() ?>",
                data: "o="+$o+"&l="+$l+"&sort="+sort_base+"&order="+order+"&fetch=1<?php echo \zinux\kernel\security\security::GetHashString(array(session_id())) ?>",
                success: function(data) {
                    window.$o += <?php echo FETCH_LIMIT; ?>
                    // unbind the success method to ignore the general result output
                    $(window).unbind('ajaxSuccess');
                    if(data.length) {
                        // append data
                        $("#explorer-table table.table").append(data);
                        // init checkboxes
                        window.init_checkboxes();
                        // update dates
                        window.update_times();
                        // re-sort table
                        window.sort_table();
                    } else {
                        $(window).unbind("scroll");
                        window.plot_if_no_item_found();
                    }
                    // set a timeout(50ms) for re-binding the ajax success method
                    setTimeout(function() { $(window).ajaxSuccess(window.ajax_success); }, 50);
                },
                error: function(xhr) {
                    window.top.open_errorModal(xhr.responseText);
                }
            }).always(function(){
                window.fetching_more = false;
                $(".ajax-loader-img-inf-scroll").addClass("hidden");
            });
        };
<?php if($active_type === 'link' || $active_type === "note"): ?>
    $(".item-row .item-name a").click(function($e){
        $e.preventDefault();
        window.top.open($(this).attr('href').split("#!")[1]);
    });
<?php endif; ?>
<?php if($this->tree_type === self::REGULAR): ?>
        window.fetching_more = false;
        $(window).scroll(function() {
            var threshold = window.pageYOffset + window.innerHeight >= document.body.scrollHeight - 200;
            if(!window.fetching_more &&  threshold) {
                window.fetch_more();
            }
        });
<?php endif; ?>
        /**
         * inits the table
         * @param boolean is_init is this is page's init call?
         */
        window.init_table =  function(is_init) {
            if(typeof(is_init) === "undefined")
                is_init = false;
            if(is_init)
                window.update_menu_checkbox();
            window.init_checkboxes();
            window.init_times();
            window.reset_ajax_placeholder(is_init);
            window.sort_table();
            window.trim_rows();
        };
        // init the table as page's init call
        window.init_table(true);
    });
</script>