<style>
    .ui-icon {
        width: 16px;
        height: 16px;
        background-image: url('/access/img/ui-icons.png');
        text-indent: -99999px;
        overflow: hidden;
        background-repeat: no-repeat;
    }
    table thead .fs-toggle {
        background-position: -128px -14px;
        display: inline-block;
        zoom: 1;
    }
    .header { cursor: pointer; }
    .header.headerSortUp .fs-toggle{
        background-position: -64px -14px;
        margin-bottom: -2px;
    }
    .header.headerSortDown .fs-toggle{
        background-position: -0px -14px;
        margin-bottom: -2px;
    }
    .header.headerSortDown,
    .header.headerSortUp {
        border-top: 1px solid #000!important;
    }        
    table#explorer-table thead tr th {
        border-top: 0!important;
    }
</style>
<form id="opt-form" method="POST" action="/ops?<?php echo \zinux\kernel\security\security::GetHashString(array($active_type, $this->request->GetURI(), session_id())) ?>">
    <input type="hidden" name="type" value="<?php echo $active_type ?>" />
    <input type="hidden" name="continue" value="<?php echo $this->request->GetURI() ?>" />
    <div id="explorer-table">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th style="width: 0.1%;"></th>
                    <th style="width: 70px;overflow: hidden" title="Status"><span class="glyphicon glyphicon-th-large"></span>&nbsp;<span class="ui-icon fs-toggle"></span></th>
                    <th style="">Name <span class="ui-icon fs-toggle"></span></th>
                    <th id="table-header-updated" style="width: 200px">Updated at <span class="ui-icon fs-toggle"></span></th>
                </tr>
            </thead>
            <tbody>