<tr class="<?php echo $type ?> item-row">
    <td>
        <?php if($is_owner) : ?><input name="items[]" class="input <?php echo $this->getCheckBoxClasses($item) ?>" related-item="<?php echo $item->WhoAmI();?>" type="checkbox" value="<?php echo $item->{"{$item->WhoAmI()}_id"}, $this->getStatusString($item), \zinux\kernel\security\security::GetHashString(array($item->WhoAmI(),  $item->{"{$item->WhoAmI()}_id"}, session_id(), \core\db\models\user::GetInstance()->user_id)); ?>" onclick="window.update_menu_checkbox();"/><?php else: ?>&nbsp;<?php endif; ?></td>
    <td class="status" status="<?php echo $this->getStatusBinary($item) ?>">
        <?php echo $this->getStatusIcons($item) ?>
    </td>
    <td class="item-name">
        <a href='<?php echo $this->getNavigationLink($item); ?>' target='<?php echo $this->getNavigationTarget($item) ?>' onclick='window.top.document.title = "/ <?php echo $item->{"{$item->WhoAmI()}_title"}; ?>";'><?php echo $item->{"{$item->WhoAmI()}_title"}; ?></a>
    </td>
    <td class="updated-at" id="<?php echo $type, '-', $item->{"{$item->WhoAmI()}_id"}?>-updated" origin-date="<?php echo $item->updated_at?>"></td>
</tr>