<tr class="<?php echo $type ?> item-row">
    <td><?php if($is_owner) : ?><input name="items[]" class="input <?php echo $this->getCheckBoxClasses($item) ?>" related-item="<?php echo $item->WhoAmI();?>" type="checkbox" value="<?php echo $this->getPostCheckVal($item); ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
    <td class="status" status="<?php echo $this->getStatusBinary($item) ?>">
        <?php echo $this->getStatusIcons($item) ?>
    </td>
    <td class="item-name filterable">
        <a href='<?php echo $this->getNavigationLink($item); ?>' target='<?php echo $this->getNavigationTarget($item) ?>'><?php echo $item->{"{$item->WhoAmI()}_title"}; ?></a>
    </td>
    <td class="updated-at timeago text-muted" id="<?php echo $type, '-', $item->{"{$item->WhoAmI()}_id"}?>-updated" origin-date="<?php echo $item->updated_at?>" title="<?php echo $item->updated_at?>"><time datetime="<?php echo $item->updated_at?>"></time></td>
</tr>