<style type="text/css">
    .step { display: none }
    #step1 { display: block!important; }
    .rep-options label {overflow:  hidden;}
    .rep-options label:hover { cursor: pointer; }
    #rep-conv .form-actions {border-top: 1px solid #DDD;margin: 10px;padding: 10px;}
    .errors > div { display: none }
</style>
<div id="rep-conv">
    <div class="select-error text-danger" style="display: none;margin-bottom: 10px;font-weight: bold">
        <span class="glyphicon glyphicon-warning-sign"></span> Please select an option first.
    </div>
    <form id="report">
        <div id="step1" class="step">
            <div class="rep-options">
                <label>
                    <input type="radio" name="reportmsg" class="input" value="spam"> Mark this conversation as spam and delete it.
                </label>
            </div>
        </div>
    </form>
    <div class="clearfix"></div>
    <div class="form-actions">
        <div class="pull-right">
            <button class="btn btn-default" id="cancel" data-dismiss="modal">Cancel</button>
            <button class="btn btn-primary" id="continue">Continue</button>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<?php // zinux\kernel\utilities\debug::_var($this->request->params, 1); ?>
<script type="text/javascript">
    $(function(){
        $("button#continue").click(function(){
            if($(".rep-options input:checked").length === 0) {
                $(".select-error").fadeIn();
                return;
            }
            $.ajax({
                url: "/messages/report/type/<?php echo $this->request->params["type"] ?>/i/<?php echo $this->request->params["i"]?>?<?php echo \zinux\kernel\security\security::__get_uri_hash_string(array($this->request->params["i"])) ?>",
                type: "POST",
                data:"submit=1&ajax=1&"+$("form#report").serialize(),
                success: function(data) {
                    window.close_modal();
                    setTimeout(function() {
                        window.open_dialogModal("<b>"+data+"</b>", 2000);
                        setTimeout(function() { window.location.reload(); }, 2000);
                    }, 500);
                }
            }).fail(function(xhr) {
                window.close_modal();
                setTimeout(function() { window.open_errorModal(xhr.responseText, -1, true); }, 500);
            });
        });
    });
</script>