<div id="send-msg">
    <form action="/send/message/to/<?php echo $this->rcv_user->username ?>?<?php echo \zinux\kernel\security\security::GetHashString(array($this->rcv_user->user_id)) ?>" method="POST" name="send-message">
<?php if(@$this->error): ?>
        <div class="text-danger" style="font-variant: small-caps;padding:10px;">» <?php echo $this->error ?></div>
<?php endif; ?>
        <div class="col-md-12">
            <div class="form-control input input-medium">
                <span class="text-info">
                    @<?php echo $this->rcv_user->username ?>
                </span>
            </div>
        </div>
        <div class="col-md-12" style="margin-top:10px;">
            <div style="max-width: 100%">
                <textarea class="form-control input input-medium" style="resize: none" rows="10" placeholder="Compose your message..." name="msg" required maxlength="500"><?php 
                    echo @$this->request->params["msg"] 
                ?></textarea>
            </div>
        </div>
        <div style="padding: 15px;">
            <div class="form-actions pull-right" style="margin-top: 10px;">
                <span id="remaining-text-length"></span> <span class="glyphicon glyphicon-pencil"></span>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-send"></span> Send
                </button>
            </div>
            <div class="clearfix"></div>
            <div class="pull-left">
<?php if($this->use_recaptcha): ?>
            <?php (new \vendor\recaptcha\recaptcha())->__render_JS(); ?>
<?php endif; ?>
            </div>
        </div>
    </form>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        setTimeout(function() { $("textarea[name='msg']").focus(); }, 500);
        // bind to update on text change
        $("textarea[name='msg']").on('keyup blur', function() {
            // Store the maxlength and value of the field.
            var maxlength = $(this).attr('maxlength');
            var val = $(this).val();
            // Trim the field if it has content over the maxlength.
            if (val.length > maxlength)
                $(this).val(val.slice(0, maxlength));
            // calc diff
            var diff = maxlength -  val.length;
            var $promt = $("#remaining-text-length");
            // promt diff
            $promt.html(diff).removeAttr('class');
            // top 25%
            if(diff > 3 * maxlength / 4)
                $promt.addClass("text-success");
            // 75% - 50%
            else if (diff > 2 * maxlength / 4)
                $promt.addClass("text-info");
            // 
            else if (diff > 1 * maxlength / 4)
                $promt.addClass("text-warning");
            else
                $promt.addClass("text-danger");
        }).blur();
<?php if(isset($this->request->params["ajax"])) : ?>
        $('form[name="send-message"]').submit(function(e) {
            e.preventDefault();
            window.close_modal();
            window.open_waitModal();
            $.ajax({
                global: false,
                url: $(this).attr('action') + "&ajax=1",
                method: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(data) {
                    var has_input = data.length;
                    if(!data.length)
                        data = "<strong><span class='glyphicon glyphicon-ok'></span> Your message sent successfully.</strong>";
                    // make a delay to close ajax modals the show the results
                    setTimeout(function() { 
                        window.open_dialogModal(data, has_input ? -1 : 2000);
                    }, 500);
                }
            }).fail(function(xhr) {
                setTimeout(function() { window.open_errorModal(xhr.responseText, -1, true); }, 500);
            }).always(function() {
                window.open_waitModal(true);
            });
        });
<?php endif; ?>
    });
</script>