<?php if(!\core\db\models\user::IsSignedin()) return; ?>
<div class="item_tableView">
<?php if(count($this->route)): ?>
<ol class="breadcrumb">
<?php
    $i = 1;
    # loading routes
    foreach ($this->route as $folder) : $is_active = ($i++==count($this->route));?>
        <li <?php echo $is_active?" class='active'":""?>><?php echo !$is_active?"<a link-type='folder' class='table-nav-link' href='/d/{$folder->folder_id}.{$this->request->type}'>":"";echo $folder->folder_title;echo !$is_active?"</a>":""?></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php if(@$this->is_owner): ?>
<ul class="nav nav-pills pull-right">
    <li class="dropdown pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plus-sign"></span> Create <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>                
                <a href="/new/folder/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("folder", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"><span class="inline glyphicon glyphicon-folder-close"></span> Folder</a>
            </li>
            <li>
                <a href="/new/note/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("note", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"><span class="glyphicon glyphicon-file"></span> Note</a>
            </li>
            <li>
                <a href="/new/link/?pid=<?php echo $this->pid.\zinux\kernel\security\security::GetHashString(array("link", $this->pid,  session_id(),  \core\db\models\user::GetInstance()->user_id))?>"><span class="glyphicon glyphicon-link"></span> Link</a>
            </li>
        </ul>
    </li>
</ul>
<?php endif ; ?>
<?php
    $this->RenderPartial("item_table", array("items" => $this->items, "pid" => $this->pid));
?>
</div>