<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            html,body{margin:0px;padding:0px;height:100%;}/*Custom page header*/.header{border-bottom:1px solid #e5e5e5;}/*Custom page footer*/.footer{padding-top:1%;color:#777;border-top:1px solid #e5e5e5;clear:both;}/*Responsive : Portrait tablets and up*/@media screen and(min-width:768px){/*Remove the padding we set earlier*/.header,.tor,.footer{padding-left:0;padding-right:0;}/*Spaceout the masthead*/.header{margin-bottom:1%;}}
        </style>
    </head>
    <body>
        <div class="container-fluid" style="">
            <?php echo $this->content; ?>
        </div>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </body>
</html>