<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
    </head>
    <body>
        <?php echo $this->content; ?>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </body>
</html>