<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <style>
            #explorer-template {position: fixed;background-color: #FFF;width: 99.7%;z-index: 10000;top:0;left:0;border: 0!important;}
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div style="padding: 10px;">
                <?php
                    $mp = new core\utiles\messagePipe;
                    $show_time = 7000;
                    while(($msg = $mp->read()))
                        if($msg)
                            \core\ui\html\alert::Tout($msg, \core\ui\html\alert::ALERT_INFO, 1, 1, ($show_time+=2000));
                ?>
                <?php echo $this->content; ?>
            </div> <!-- end of padder -->
        </div><!-- end of container -->
        <script>
            (function() {
                // if we have directory jumped into explorer frame
                if(window.top === window) {
                    // redirect the URL
                    window.location = "/#!" + window.location.pathname;
                    return;
                }
                window.setTitle = function (title) {window.top.document.title = title;};
                window.getLinkHash = function(link) { return "#!/"+String(link).replace(/^(\/frame\/e)?(\/)?/ig,""); };
                window.updateHash = function(hash) { window.top.location.replace(String(window.top.location).split("#")[0] + hash); };
                window.setTitle($("#explorer-template ol.breadcrumb li.active").text().trim());
                window.updateHash(window.getLinkHash('<?php echo $this->request->getURI(); ?>'));
                $("a").click(function(e){
                    if($(this).is("[href]") && $(this).attr("href").length && $(this).attr("href")[0] !== "#") {
                        e.preventDefault();
                        window.location = $(this).attr('href');
                        window.updateHash(window.getLinkHash($(this).attr("href")));
                    }
                });
            })(jQuery);
        </script>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </body>
</html>