<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>
    </head>
    <body id="body-frame">
        <iframe id="explorer-nav-frame" style="border-style: none; border-color: inherit; border-width: 0px;width: 20%;height: 1000px" src="/frame/en"></iframe>
        <iframe id="explorer-frame" style="border-style: none; border-color: inherit; border-width: 0px;width: 59.5%;height: 1000px" src="/frame/e"></iframe>
        <iframe id="feed-frame" style="border-style: none; border-color: inherit; border-width: 0px;width: 20%;float: right;height: 1000px" src="/frame/f"></iframe>
    </body>
</html>