<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sign up page">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <link rel="shortcut icon" href="/favicon.ico">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            html,body{margin:0px;padding:0px;height:100%;}/*Custom page header*/.header{border-bottom:1px solid #e5e5e5;}/*Custom page footer*/.footer{padding-top:1%;color:#777;border-top:1px solid #e5e5e5;clear:both;}/*Responsive : Portrait tablets and up*/@media screen and(min-width:768px){/*Remove the padding we set earlier*/.header,.tor,.footer{padding-left:0;padding-right:0;}/*Spaceout the masthead*/.header{margin-bottom:1%;}}/*iframe gen. attribs */iframe{width:100%;border-style:none;border-color:transparent;border-width:0px;}
        </style>
    </head>
    <body>
        <noscript>
            <?php \core\ui\html\alert::Cout("!!Your browser's javascript IS NOT enabled!!", \core\ui\html\alert::ALERT_DANGER); ?>
        </noscript>
        <div class="header">
            <ul class="nav nav-pills pull-right" style="padding-top: 0.25%;">
                <?php if(($user_logged = \core\db\models\user::IsSignedin())): ?>
                <li class='hidden-lg hidden-md'><a href='#'><span class='glyphicon glyphicon-flash'></span> Feeds</a></li>
                <li><a href="#"><span class="badge">0</span> Messages</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge">2</span> Notifications<b class="caret"></b></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="#">Some stuff</a></li>
                        <li><a href="#">Some other stuff</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <?php list($avatar_uri , $def_avatar) = \core\ui\html\avatar::get_avatar_link(\core\db\models\user::GetInstance()->user_id); ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src='<?php echo $avatar_uri ?>' height="20" width="20" class='imageblock img-rounded' onerror="this.src='<?php echo $def_avatar ?>'"/> Account <b class="caret"></b></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="/profile">Profile</a></li>
                        <li><a href="#">Account Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="/signout">Signout</a></li>
                    </ul>
                </li>
                <?php else: ?>
                    <li><a href="/signin">Signin</a></li>
                    <li><a href="/signup">Signup</a></li>
                <?php endif; ?>
            </ul>
            <a href="/" style="font-size: x-large;" class="navbar-brand text-muted" >Toratan</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <script>
            (function() {
                window.default_modal_button = new (function() {
                    this.get = function() { return {
                                    html: "Close",
                                    attrib: [
                                        {key: "name", value: "close"},
                                        {key: "data-dismiss", value: "modal"}
                                    ],
                                    cssClass: ["btn-primary"],
                                    callback: null
                                }; 
                    };
                });
                /**
                 * Opens a modal
                 * @param string modal_tag the target modal tag
                 * @param string data the data to put into modal body
                 * @param integer close_timeout the timeout for closing modal
                 * @param array __button and array of button informations to add to modal { default: close button }
                 * @notice __button : each entity should have a format of following {html: 'html context string of button', attrib: ' array attributes of  button', cssClass: 'array of css classes', callback: 'call back function of button'
                 * 
                 */
                window.open_modal = function(modal_tag, data, title, close_timeout, __buttons) {
                    if(typeof(title) === 'undefined') title = '<span class="glyphicon glyphicon-info-sign"></span> Dialog';
                    if(typeof(close_timeout) === 'undefined') close_timeout = -1;
                    if(typeof(__buttons) === 'undefined') {
                        __buttons = [ default_modal_button.get() ];
                    }
                    $(modal_tag+" .modal-body").html(data);
                    $(modal_tag+" .modal-title").html(title);
                    $(modal_tag+" .modal-footer").html('');
                    for(var index = 0; index < __buttons.length; index++) {
                        var b = __buttons[index];
                        if(typeof(b.html) === 'undefined') {
                            throw "No `html` property defined for button";
                        }
                        var btn_id = "modal-btn-"+(String(modal_tag).replace(/(\.|#)/ig, "", modal_tag))+"-"+index.toString();
                        var t = '<button id="'+btn_id+'" type="button" class="btn ';
                        for(var cssclass = 0; cssclass <  b.cssClass.length; cssclass++) {
                            t += " "+b.cssClass[cssclass];
                        }
                        t += '"'; // for classes
                        for(var attribIndex = 0; attribIndex <  b.attrib.length, typeof(b.attrib[attribIndex]) !== "undefined"; attribIndex++) {
                           t += " " + b.attrib[attribIndex].key + "='" + b.attrib[attribIndex].value+"'";
                       }
                        t += (">"+b.html + '</button>');
                        $(modal_tag+" .modal-footer").append(t).html();
                        if(typeof(b.callback) !== 'undefined' && b.callback !== null) {
                            $(modal_tag+" .modal-footer button#"+btn_id).click(function() {
                                var callback = b.callback;
                                // we have to do this to prevent a UI bug
                                $(modal_tag).on('hidden.bs.modal', function () {
                                    // unregister current handler
                                    // we don't want to repeat this handler
                                    // at next modal show/hidden!!
                                    $(this).off('hidden.bs.modal');
                                    // call the callback
                                    callback();
                                }).modal('hide');
                            });
                        }
                    }
                    $(modal_tag).modal('show');
                    if(close_timeout > 0) {
                        setTimeout(function(tag){
                            $(tag).modal('hide');
                        }, close_timeout, modal_tag);
                    }
                };
                /**
                 * open an info modal  
                 * @param string info the info to put into modal body
                 * @param integer close_timeout the timeout for closing modal
                 */
                window.open_infoModal = function(info, close_timeout) {
                    open_modal("div#dialog-modal", info, '<span class="glyphicon glyphicon-comment"></span> Notice', close_timeout);
                };
                /**
                 * open an error modal  
                 * @param string info the info to put into modal body
                 * @param integer close_timeout the timeout for closing modal
                 */
                window.open_errorModal = function(info, close_timeout) {
                    open_modal("div#dialog-modal", info, '<span class="glyphicon glyphicon-remove-sign"></span> Oops!', close_timeout);
                };
                /**
                 * open a YES/NO modal
                 * @param string info the info to put into modal body
                 * @param function yes_callback
                 * @param function no_callback
                 * @param boolean is_yes_primary check if `YES` is primary or `NO`
                 * @param integer close_timeout the timeout for closing modal
                 */
                window.open_yesnoModal = function(info, yes_callback, no_callback, is_yes_primary, close_timeout) {
                    if(typeof(is_yes_primary) === "undefined") is_yes_primary = 1;
                    var yes = default_modal_button.get();
                    var no = default_modal_button.get();
                    yes.callback = yes_callback;
                    no.callback = no_callback;
                    yes.html = "Yes";
                    no.html = "No";
                    yes.attrib[0].value = "yes";
                    no.attrib[0].value = "no";
                    if(is_yes_primary) {
                        delete yes.attrib[1];
                        no.cssClass[0] = "btn-default";
                    } else {
                        delete no.attrib[1];
                        yes.cssClass[0] = "btn-default";
                    }
                    open_modal("div#dialog-modal", info, '<span class="glyphicon glyphicon-question-sign"></span> Confirm', close_timeout, [no, yes]);
                };
                window.active_nav = function(id) {
                    $('#explorer-nav-frame').contents().find("div#exp-nav ul.nav li a[target='explorer-frame']").parent().removeClass("active");
                    $('#explorer-nav-frame').contents().find("div#exp-nav ul.nav li a[target='explorer-frame']#"+id).parent().addClass("active");
                };
                window.getActiveType = function() {
                    return String($('#explorer-nav-frame').contents().find("div#exp-nav ul.nav li.active").find("a").attr("id")).toLowerCase();
                };
                window.getActiveNavHtml = function() {
                    var $anh = $('#explorer-nav-frame').contents().find("div#exp-nav ul.nav li.active a[target='explorer-frame']").clone();
                    return $anh.removeAttr("user-data")
                            .removeAttr("target")
                                .wrap('<p/>').parent().html();
                };
                window.getActiveTypeLink = function() {
                    return $('#explorer-nav-frame').contents().find("div#exp-nav ul.nav li a[target='explorer-frame']#"+window.getActiveType()).attr('href');
                };
            })(jQuery);
        </script>
        <!-- general modal -->
        <div id="dialog-modal" class="modal fade" role="dialog" aria-labelledby="ops-container-info" aria-hidden="true" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
              </div>
              <div class="modal-body"></div>
              <div class="modal-footer"></div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <div class="container-fluid" style="padding-top:0.5%">
        <?php if($user_logged) :  ?>
            <iframe id="explorer-nav-frame" name="explorer-nav-frame" frameborder="0" style="height: 250px" src="/frame/en" class="pull-left col-lg-2 col-md-2 col-sm-3 col-xm-3"></iframe>
            <iframe id="explorer-frame" name="explorer-frame" frameborder="0" style="height: 768px" src="" class="col-lg-7 col-md-7 col-sm-9 col-xm-9"></iframe>
            <iframe id="feed-frame" name="feed-frame" frameborder="0" style="height: 768px" src="/frame/f" class="pull-right col-lg-3 col-md-3 hidden-sm hidden-xs"></iframe>
        <?php else: ?>
            <legend>Not logged in {Fames go here!!}</legend>
        <?php endif; ?>
        </div>
        <script type="text/javascript">
            (function(){
                // modify frames' size on window resize event
                $(window).resize(function() {
                    var $frames = $('iframe#explorer-frame, iframe#feed-frame');
                    if($(window).height() >= 420)
                        // re-size the frames
                        $frames.css('height', ($(window).height() - 90)+'px');
                    else
                        $frames.css('height', '768px');
                });
                // init frames' size to window's size
                $(window).resize();
                // re-locate the explorer
                $('#explorer-nav-frame').attr('src', '/frame/en/'+window.location.hash);
            })(jQuery);
        </script>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </body>
</html>