<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sign up page">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <!-- jQuery -->
        <script type="text/javascript" src="/access/js/jquery-1.10.2.min.js"></script>
        <link rel="shortcut icon" href="/favicon.ico">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style>
            html,body{margin:0px;padding:0px;height:100%;}/*Custom page header*/.header{border-bottom:1pxsolid#e5e5e5;}/*Custom page footer*/.footer{padding-top:1%;color:#777;border-top:1pxsolid#e5e5e5;clear:both;}/*Responsive : Portrait tablets and up*/@media screen and(min-width:768px){/*Remove the padding we set earlier*/.header,.tor,.footer{padding-left:0;padding-right:0;}/*Spaceout the masthead*/.header{margin-bottom:1%;}}/*iframe gen. attribs */iframe{width:100%;border-style:none;border-color:inherit;border-width:0px;}
        </style>
    </head>
    <body>
        <noscript>
            <?php \core\ui\html\alert::Cout("!!Your browser's javascript IS NOT enabled!!", \core\ui\html\alert::ALERT_DANGER); ?>
        </noscript>
        <div class="header">
            <ul class="nav nav-pills pull-right" style="padding-top: 0.25%;">
                <?php if(($user_logged = \core\db\models\user::IsSignedin())): ?>
                <li class='hidden-lg hidden-md'><a href='#'><span class='glyphicon glyphicon-flash'></span> Feeds</a></li>
                <li><a href="#"><span class="badge">0</span> Messages</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge">2</span> Notifications<b class="caret"></b></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="#">Some stuff</a></li>
                        <li><a href="#">Some other stuff</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <?php list($avatar_uri , $def_avatar) = \core\ui\html\avatar::get_avatar_link(\core\db\models\user::GetInstance()->user_id); ?>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src='<?php echo $avatar_uri ?>' height="20" width="20" class='imageblock img-rounded' onerror="this.src='<?php echo $def_avatar ?>'"/> Account <b class="caret"></b></a>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="/profile">Profile</a></li>
                        <li><a href="#">Account Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="/signout">Signout</a></li>
                    </ul>
                </li>
                <?php else: ?>
                    <li><a href="/signin">Signin</a></li>
                    <li><a href="/signup">Signup</a></li>
                <?php endif; ?>
            </ul>
            <a href="/" style="font-size: x-large;" class="navbar-brand text-muted" >Toratan</a>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <div class="container-fluid">
        <?php if($user_logged) :  ?>
            <script>
                $(document).ready(function() {
                    $('#explorer-nav-frame').attr('src', '/frame/en/'+window.location.hash);
                });
            </script>
            <iframe id="explorer-nav-frame" name="explorer-nav-frame" style="height: 300px" src="/frame/en" class="pull-left col-lg-2 col-md-2 col-sm-3 col-xm-3"></iframe>
            <iframe id="explorer-frame" name="explorer-frame" style="height: 768px" src="" class="col-lg-7 col-md-7 col-sm-9 col-xm-9"></iframe>
            <iframe id="feed-frame" name="feed-frame" style="height: 768px" src="/frame/f" class="pull-right col-lg-3 col-md-3 hidden-sm hidden-xs"></iframe>
        <?php else: ?>
            <legend>Not logged in {Fames go here!!}</legend>
        <?php endif; ?>
        </div>
        <script type="text/javascript" src="/access/js/bootstrap.min.js"></script>
    </body>
</html>