<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- twitter bootstrap -->
        <link rel="stylesheet" href="/access/css/bootstrap.min.css">
        <link rel="stylesheet" href="/access/css/bootstrap-theme.min.css">
        <link rel="shortcut icon" href="/favicon.ico">
        <?php $this->RenderTitle();?>
        <?php $this->RenderImports(); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <style type="text/css">
            html,body{margin:0px;padding:0px;height:100%;}/*Custom page header*/.header{border-bottom:1px solid #e5e5e5;}/*Custom page footer*/.footer{padding-top:1%;color:#777;border-top:1px solid #e5e5e5;clear:both;}/*Responsive : Portrait tablets and up*/@media screen and(min-width:768px){/*Remove the padding we set earlier*/.header,.tor,.footer{padding-left:0;padding-right:0;}/*Spaceout the masthead*/.header{margin-bottom:1%;}}/*iframe gen. attribs */iframe{width:100%;border-style:none;border-color:transparent;border-width:0px;}
        </style>
    </head>
    <body>
        <div class="header">
            <a href="/" style="font-size: x-large;" class="navbar-brand text-muted">Toratan</a>
            <div class="clearfix"></div>
        </div>
        <script type="text/javascript">
            (function(){
                // if we are in a frame?
                if(window.top !== window.self)
                    // remove the header
                    $(".header").remove();
            })(jQuery);
        </script>
        <div class="clearfix" style="margin-top:10px;"></div>
        <div id="error-layout">
            <style type="text/css">
                .error-container {width: 580px;padding: 20px;margin: 10px auto;border: 1px solid #cccccc;}
                .error-header { border-bottom: 1px solid #cccccc; padding-bottom: 10px; font-weight: bold}
                .error-body {text-align: justify; padding: 10px; font-size: 15px}
                .eref {font-family: monospace;cursor: pointer;width: 98%;overflow: auto}
            </style>
            <script type="text/javascript">
                (function(){
                    // if i am in a frame?
                    if(window.top !== window.self)
                        window.top.document.title = '<?php echo $this->getTitle() ?>';
                })(jQuery);
            </script>
            <div class="container">
                <div class="error-container">
                    <?php echo $this->content; ?>
                    <div class="clearfix"></div>
                    <small style="padding: 10px;">
                        » <a href="/">Return home</a>
                        <?php if(@$this->view->eref): ?>
                        <span class="pull-right text-muted eref text-right" title="While trying contact us regarding to this error please pass the #">
                            Reference# <?php
                                $should_link_ref = \core\db\models\user::IsSignedin() && 
                                        (@\core\db\models\user::GetInstance()->user_type == \core\db\models\user::USER_TYPE_ADMINISTRATOR || 
                                        @\core\db\models\user::GetInstance()->user_type == \core\db\models\user::USER_TYPE_DEVELOPER)
                            ?><?php echo $should_link_ref ? "<a href='/error/view/{$this->view->eref}' title='View error detail'>" : "", $this->view->eref, $should_link_ref ? "</a>" : "" ?>
                        </span>
                        <?php endif; ?>
                    </small>
                    <div class="block" style="margin: 5px"></div>
                </div>
            </div>
        </div>
    </body>
</html>