<?php $glayout = new \modules\defaultModule\views\layout\genLayoutHeader($this); ?>
<?php $glayout->render_header(); ?>
<div id="error-layout">
    <style type="text/css">
        .error-container {width: 580px;padding: 20px;margin: 10px auto;border: 1px solid #cccccc;}
        .error-header { border-bottom: 1px solid #cccccc; padding-bottom: 10px; font-weight: bold}
        .error-body {text-align: justify; padding: 10px; font-size: 15px}
        .eref {font-family: monospace;cursor: pointer;width: 98%;overflow: auto}
    </style>
    <script type="text/javascript">
        (function(){
            // if i am in a frame?
            if(window.top !== window.self)
                window.top.document.title = '<?php echo $this->getTitle() ?>';
        })(jQuery);
    </script>
    <div class="container">
        <div class="error-container">
            <?php echo $this->content; ?>
            <div class="clearfix"></div>
            <small style="padding: 10px;">
                » <a href="/">Return home</a>
                <span class="pull-right text-muted eref text-right" title="While trying contact us regarding to this error please pass the #">
                    Reference# <?php echo $this->view->eref ?>
                </span>
            </small>
            <div class="block" style="margin: 5px"></div>
        </div>
    </div>
</div>
<?php $glayout->render_footer(); ?>